// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authnmock

import (
	"context"

	"github.com/dashkan/pivox/internal/authn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateCustomToken provides a mock function for the type MockService
func (_mock *MockService) CreateCustomToken(ctx context.Context, uid string) (string, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateCustomToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomToken'
type MockService_CreateCustomToken_Call struct {
	*mock.Call
}

// CreateCustomToken is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockService_Expecter) CreateCustomToken(ctx interface{}, uid interface{}) *MockService_CreateCustomToken_Call {
	return &MockService_CreateCustomToken_Call{Call: _e.mock.On("CreateCustomToken", ctx, uid)}
}

func (_c *MockService_CreateCustomToken_Call) Run(run func(ctx context.Context, uid string)) *MockService_CreateCustomToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateCustomToken_Call) Return(s string, err error) *MockService_CreateCustomToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_CreateCustomToken_Call) RunAndReturn(run func(ctx context.Context, uid string) (string, error)) *MockService_CreateCustomToken_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOidcProvider provides a mock function for the type MockService
func (_mock *MockService) CreateOidcProvider(ctx context.Context, cfg authn.OidcProviderConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for CreateOidcProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authn.OidcProviderConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateOidcProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOidcProvider'
type MockService_CreateOidcProvider_Call struct {
	*mock.Call
}

// CreateOidcProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg authn.OidcProviderConfig
func (_e *MockService_Expecter) CreateOidcProvider(ctx interface{}, cfg interface{}) *MockService_CreateOidcProvider_Call {
	return &MockService_CreateOidcProvider_Call{Call: _e.mock.On("CreateOidcProvider", ctx, cfg)}
}

func (_c *MockService_CreateOidcProvider_Call) Run(run func(ctx context.Context, cfg authn.OidcProviderConfig)) *MockService_CreateOidcProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authn.OidcProviderConfig
		if args[1] != nil {
			arg1 = args[1].(authn.OidcProviderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateOidcProvider_Call) Return(err error) *MockService_CreateOidcProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateOidcProvider_Call) RunAndReturn(run func(ctx context.Context, cfg authn.OidcProviderConfig) error) *MockService_CreateOidcProvider_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSamlProvider provides a mock function for the type MockService
func (_mock *MockService) CreateSamlProvider(ctx context.Context, cfg authn.SamlProviderConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSamlProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authn.SamlProviderConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateSamlProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSamlProvider'
type MockService_CreateSamlProvider_Call struct {
	*mock.Call
}

// CreateSamlProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg authn.SamlProviderConfig
func (_e *MockService_Expecter) CreateSamlProvider(ctx interface{}, cfg interface{}) *MockService_CreateSamlProvider_Call {
	return &MockService_CreateSamlProvider_Call{Call: _e.mock.On("CreateSamlProvider", ctx, cfg)}
}

func (_c *MockService_CreateSamlProvider_Call) Run(run func(ctx context.Context, cfg authn.SamlProviderConfig)) *MockService_CreateSamlProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authn.SamlProviderConfig
		if args[1] != nil {
			arg1 = args[1].(authn.SamlProviderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateSamlProvider_Call) Return(err error) *MockService_CreateSamlProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateSamlProvider_Call) RunAndReturn(run func(ctx context.Context, cfg authn.SamlProviderConfig) error) *MockService_CreateSamlProvider_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOidcProvider provides a mock function for the type MockService
func (_mock *MockService) DeleteOidcProvider(ctx context.Context, providerID string) error {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOidcProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteOidcProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOidcProvider'
type MockService_DeleteOidcProvider_Call struct {
	*mock.Call
}

// DeleteOidcProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockService_Expecter) DeleteOidcProvider(ctx interface{}, providerID interface{}) *MockService_DeleteOidcProvider_Call {
	return &MockService_DeleteOidcProvider_Call{Call: _e.mock.On("DeleteOidcProvider", ctx, providerID)}
}

func (_c *MockService_DeleteOidcProvider_Call) Run(run func(ctx context.Context, providerID string)) *MockService_DeleteOidcProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteOidcProvider_Call) Return(err error) *MockService_DeleteOidcProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteOidcProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string) error) *MockService_DeleteOidcProvider_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSamlProvider provides a mock function for the type MockService
func (_mock *MockService) DeleteSamlProvider(ctx context.Context, providerID string) error {
	ret := _mock.Called(ctx, providerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSamlProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteSamlProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSamlProvider'
type MockService_DeleteSamlProvider_Call struct {
	*mock.Call
}

// DeleteSamlProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerID string
func (_e *MockService_Expecter) DeleteSamlProvider(ctx interface{}, providerID interface{}) *MockService_DeleteSamlProvider_Call {
	return &MockService_DeleteSamlProvider_Call{Call: _e.mock.On("DeleteSamlProvider", ctx, providerID)}
}

func (_c *MockService_DeleteSamlProvider_Call) Run(run func(ctx context.Context, providerID string)) *MockService_DeleteSamlProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteSamlProvider_Call) Return(err error) *MockService_DeleteSamlProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteSamlProvider_Call) RunAndReturn(run func(ctx context.Context, providerID string) error) *MockService_DeleteSamlProvider_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockService
func (_mock *MockService) DeleteUser(ctx context.Context, uid string) error {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
func (_e *MockService_Expecter) DeleteUser(ctx interface{}, uid interface{}) *MockService_DeleteUser_Call {
	return &MockService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, uid)}
}

func (_c *MockService_DeleteUser_Call) Run(run func(ctx context.Context, uid string)) *MockService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteUser_Call) Return(err error) *MockService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, uid string) error) *MockService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOidcProvider provides a mock function for the type MockService
func (_mock *MockService) UpdateOidcProvider(ctx context.Context, cfg authn.OidcProviderConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOidcProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authn.OidcProviderConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateOidcProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOidcProvider'
type MockService_UpdateOidcProvider_Call struct {
	*mock.Call
}

// UpdateOidcProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg authn.OidcProviderConfig
func (_e *MockService_Expecter) UpdateOidcProvider(ctx interface{}, cfg interface{}) *MockService_UpdateOidcProvider_Call {
	return &MockService_UpdateOidcProvider_Call{Call: _e.mock.On("UpdateOidcProvider", ctx, cfg)}
}

func (_c *MockService_UpdateOidcProvider_Call) Run(run func(ctx context.Context, cfg authn.OidcProviderConfig)) *MockService_UpdateOidcProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authn.OidcProviderConfig
		if args[1] != nil {
			arg1 = args[1].(authn.OidcProviderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateOidcProvider_Call) Return(err error) *MockService_UpdateOidcProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateOidcProvider_Call) RunAndReturn(run func(ctx context.Context, cfg authn.OidcProviderConfig) error) *MockService_UpdateOidcProvider_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSamlProvider provides a mock function for the type MockService
func (_mock *MockService) UpdateSamlProvider(ctx context.Context, cfg authn.SamlProviderConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSamlProvider")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, authn.SamlProviderConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateSamlProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSamlProvider'
type MockService_UpdateSamlProvider_Call struct {
	*mock.Call
}

// UpdateSamlProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg authn.SamlProviderConfig
func (_e *MockService_Expecter) UpdateSamlProvider(ctx interface{}, cfg interface{}) *MockService_UpdateSamlProvider_Call {
	return &MockService_UpdateSamlProvider_Call{Call: _e.mock.On("UpdateSamlProvider", ctx, cfg)}
}

func (_c *MockService_UpdateSamlProvider_Call) Run(run func(ctx context.Context, cfg authn.SamlProviderConfig)) *MockService_UpdateSamlProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 authn.SamlProviderConfig
		if args[1] != nil {
			arg1 = args[1].(authn.SamlProviderConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateSamlProvider_Call) Return(err error) *MockService_UpdateSamlProvider_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateSamlProvider_Call) RunAndReturn(run func(ctx context.Context, cfg authn.SamlProviderConfig) error) *MockService_UpdateSamlProvider_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function for the type MockService
func (_mock *MockService) VerifyToken(ctx context.Context, token string) (*authn.Identity, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *authn.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authn.Identity, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authn.Identity); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authn.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockService_VerifyToken_Call {
	return &MockService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockService_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyToken_Call) Return(identity *authn.Identity, err error) *MockService_VerifyToken_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockService_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*authn.Identity, error)) *MockService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
