// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authnmock

import (
	"context"

	"github.com/dashkan/pivox/internal/authn"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// VerifyToken provides a mock function for the type MockService
func (_mock *MockService) VerifyToken(ctx context.Context, token string) (*authn.Identity, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *authn.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authn.Identity, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authn.Identity); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authn.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockService_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockService_VerifyToken_Call {
	return &MockService_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockService_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockService_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_VerifyToken_Call) Return(identity *authn.Identity, err error) *MockService_VerifyToken_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockService_VerifyToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*authn.Identity, error)) *MockService_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}
