// protoc-gen-pivox-swift-protobridge
//
// Emits Swift extensions on swift-protobuf generated message types so
// C++ can read/write proto bytes through the Swift-C++ interop seam:
//
//	extension Foo {
//	    func serializedBytesArray() -> [UInt8] { ... }
//	    static func parse(fromBytes b: [UInt8]) -> Foo { ... }
//	}
//
// swift-protobuf's native serializer is generic + throwing and doesn't
// project to C++. These concrete wrappers do.
//
// Retirement trigger: swift-protobuf upstream ships non-generic,
// non-throwing `serializedBytes()` / `init(fromBytes:)` helpers that
// Swift-C++ interop projects directly. This plugin can then be deleted.
package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/dashkan/pivox/tools/internal/pivoxgen"
)

func main() {
	var flags flag.FlagSet
	var opts pivoxgen.CommonOptions
	pivoxgen.RegisterCommonFlags(&flags, &opts)

	protogen.Options{ParamFunc: flags.Set}.Run(func(p *protogen.Plugin) error {
		pivoxgen.SetSupportedFeatures(p)

		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			if len(f.Messages) == 0 {
				continue
			}
			name, content := EmitBridge(f)
			g := p.NewGeneratedFile(name, "")
			g.P(content)
		}
		return nil
	})
}

// EmitBridge builds the (filename, content) pair for one input proto
// file's Swift bridge extensions. Pure function — called by main for
// the real pipeline and by tests for golden-file comparison.
func EmitBridge(f *protogen.File) (filename, content string) {
	// Flat filename matching swift-protobuf's `FileNaming=PathToUnderscores`
	// convention so our bridge files sit next to the pb.swift files with
	// no collisions between e.g. `pivox/agent/v1/agent.proto` and
	// `pivox/storage/v1/agent.proto`.
	protoPath := f.Desc.Path()
	trimmed := strings.TrimSuffix(protoPath, ".proto")
	flat := strings.ReplaceAll(trimmed, "/", "_")
	filename = fmt.Sprintf("%s.bridge.swift", flat)

	var b strings.Builder
	fmt.Fprintln(&b, "// Generated by protoc-gen-pivox-swift-protobridge. DO NOT EDIT.")
	fmt.Fprintln(&b, "// source:", protoPath)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "import SwiftProtobuf")
	fmt.Fprintln(&b)

	prefix := swiftPrefix(string(f.Desc.Package()))
	for _, m := range f.Messages {
		typeName := prefix + string(m.Desc.Name())
		fmt.Fprintf(&b, "public extension %s {\n", typeName)
		fmt.Fprintln(&b, "    func serializedBytesArray() -> [UInt8] {")
		fmt.Fprintln(&b, "        (try? serializedBytes()) ?? []")
		fmt.Fprintln(&b, "    }")
		fmt.Fprintf(&b, "    static func parse(fromBytes b: [UInt8]) -> %s {\n", typeName)
		fmt.Fprintln(&b, "        (try? Self(serializedBytes: b)) ?? Self()")
		fmt.Fprintln(&b, "    }")
		fmt.Fprintln(&b, "}")
		fmt.Fprintln(&b)
	}
	return filename, b.String()
}

// swiftPrefix converts a proto package like "pivox.ai.v1" into the
// Swift-protobuf type prefix "Pivox_Ai_V1_". Empty package → empty
// prefix. Matches swift-protobuf's default type-naming rule.
func swiftPrefix(pkg string) string {
	if pkg == "" {
		return ""
	}
	parts := strings.Split(pkg, ".")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "_") + "_"
}
