/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthCreateOrgRouteImport } from './routes/auth/create-org'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppImageEditorRouteImport } from './routes/_app/image-editor'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app/workflows/index'
import { Route as AppSecretsIndexRouteImport } from './routes/_app/secrets/index'
import { Route as AppConnectorsIndexRouteImport } from './routes/_app/connectors/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app/workflows/$workflowId'
import { Route as AppSecretsNewRouteImport } from './routes/_app/secrets/new'
import { Route as AppConnectorsNewRouteImport } from './routes/_app/connectors/new'
import { Route as AppSecretsSecretIdEditRouteImport } from './routes/_app/secrets/$secretId.edit'
import { Route as AppConnectorsConnectorIdEditRouteImport } from './routes/_app/connectors/$connectorId.edit'

const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCreateOrgRoute = AuthCreateOrgRouteImport.update({
  id: '/auth/create-org',
  path: '/auth/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppImageEditorRoute = AppImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsIndexRoute = AppSecretsIndexRouteImport.update({
  id: '/secrets/',
  path: '/secrets/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsIndexRoute = AppConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => AppRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsNewRoute = AppSecretsNewRouteImport.update({
  id: '/secrets/new',
  path: '/secrets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsNewRoute = AppConnectorsNewRouteImport.update({
  id: '/connectors/new',
  path: '/connectors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSecretsSecretIdEditRoute = AppSecretsSecretIdEditRouteImport.update({
  id: '/secrets/$secretId/edit',
  path: '/secrets/$secretId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsConnectorIdEditRoute =
  AppConnectorsConnectorIdEditRouteImport.update({
    id: '/connectors/$connectorId/edit',
    path: '/connectors/$connectorId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/launch': typeof LaunchRoute
  '/about': typeof AppAboutRoute
  '/image-editor': typeof AppImageEditorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/create-org': typeof AuthCreateOrgRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/connectors/new': typeof AppConnectorsNewRoute
  '/secrets/new': typeof AppSecretsNewRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/connectors/': typeof AppConnectorsIndexRoute
  '/secrets/': typeof AppSecretsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/connectors/$connectorId/edit': typeof AppConnectorsConnectorIdEditRoute
  '/secrets/$secretId/edit': typeof AppSecretsSecretIdEditRoute
}
export interface FileRoutesByTo {
  '/launch': typeof LaunchRoute
  '/about': typeof AppAboutRoute
  '/image-editor': typeof AppImageEditorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/create-org': typeof AuthCreateOrgRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof AppIndexRoute
  '/connectors/new': typeof AppConnectorsNewRoute
  '/secrets/new': typeof AppSecretsNewRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/connectors': typeof AppConnectorsIndexRoute
  '/secrets': typeof AppSecretsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/connectors/$connectorId/edit': typeof AppConnectorsConnectorIdEditRoute
  '/secrets/$secretId/edit': typeof AppSecretsSecretIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/launch': typeof LaunchRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/image-editor': typeof AppImageEditorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/create-org': typeof AuthCreateOrgRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/connectors/new': typeof AppConnectorsNewRoute
  '/_app/secrets/new': typeof AppSecretsNewRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/connectors/': typeof AppConnectorsIndexRoute
  '/_app/secrets/': typeof AppSecretsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/connectors/$connectorId/edit': typeof AppConnectorsConnectorIdEditRoute
  '/_app/secrets/$secretId/edit': typeof AppSecretsSecretIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch'
    | '/about'
    | '/image-editor'
    | '/auth/callback'
    | '/auth/create-org'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/connectors/new'
    | '/secrets/new'
    | '/workflows/$workflowId'
    | '/api/v1/$'
    | '/connectors/'
    | '/secrets/'
    | '/workflows/'
    | '/connectors/$connectorId/edit'
    | '/secrets/$secretId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/launch'
    | '/about'
    | '/image-editor'
    | '/auth/callback'
    | '/auth/create-org'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/'
    | '/connectors/new'
    | '/secrets/new'
    | '/workflows/$workflowId'
    | '/api/v1/$'
    | '/connectors'
    | '/secrets'
    | '/workflows'
    | '/connectors/$connectorId/edit'
    | '/secrets/$secretId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/launch'
    | '/_app/about'
    | '/_app/image-editor'
    | '/auth/callback'
    | '/auth/create-org'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/_app/'
    | '/_app/connectors/new'
    | '/_app/secrets/new'
    | '/_app/workflows/$workflowId'
    | '/api/v1/$'
    | '/_app/connectors/'
    | '/_app/secrets/'
    | '/_app/workflows/'
    | '/_app/connectors/$connectorId/edit'
    | '/_app/secrets/$secretId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LaunchRoute: typeof LaunchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthCreateOrgRoute: typeof AuthCreateOrgRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/create-org': {
      id: '/auth/create-org'
      path: '/auth/create-org'
      fullPath: '/auth/create-org'
      preLoaderRoute: typeof AuthCreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/image-editor': {
      id: '/_app/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof AppImageEditorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets/': {
      id: '/_app/secrets/'
      path: '/secrets'
      fullPath: '/secrets/'
      preLoaderRoute: typeof AppSecretsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/': {
      id: '/_app/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AppConnectorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets/new': {
      id: '/_app/secrets/new'
      path: '/secrets/new'
      fullPath: '/secrets/new'
      preLoaderRoute: typeof AppSecretsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/new': {
      id: '/_app/connectors/new'
      path: '/connectors/new'
      fullPath: '/connectors/new'
      preLoaderRoute: typeof AppConnectorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/secrets/$secretId/edit': {
      id: '/_app/secrets/$secretId/edit'
      path: '/secrets/$secretId/edit'
      fullPath: '/secrets/$secretId/edit'
      preLoaderRoute: typeof AppSecretsSecretIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/$connectorId/edit': {
      id: '/_app/connectors/$connectorId/edit'
      path: '/connectors/$connectorId/edit'
      fullPath: '/connectors/$connectorId/edit'
      preLoaderRoute: typeof AppConnectorsConnectorIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppImageEditorRoute: typeof AppImageEditorRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConnectorsNewRoute: typeof AppConnectorsNewRoute
  AppSecretsNewRoute: typeof AppSecretsNewRoute
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppConnectorsIndexRoute: typeof AppConnectorsIndexRoute
  AppSecretsIndexRoute: typeof AppSecretsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
  AppConnectorsConnectorIdEditRoute: typeof AppConnectorsConnectorIdEditRoute
  AppSecretsSecretIdEditRoute: typeof AppSecretsSecretIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppImageEditorRoute: AppImageEditorRoute,
  AppIndexRoute: AppIndexRoute,
  AppConnectorsNewRoute: AppConnectorsNewRoute,
  AppSecretsNewRoute: AppSecretsNewRoute,
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppConnectorsIndexRoute: AppConnectorsIndexRoute,
  AppSecretsIndexRoute: AppSecretsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
  AppConnectorsConnectorIdEditRoute: AppConnectorsConnectorIdEditRoute,
  AppSecretsSecretIdEditRoute: AppSecretsSecretIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LaunchRoute: LaunchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthCreateOrgRoute: AuthCreateOrgRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignInRoute: AuthSignInRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
