/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLinkAccountRouteImport } from './routes/auth/link-account'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthElectronLoginRouteImport } from './routes/auth/electron-login'
import { Route as AuthElectronLinkRouteImport } from './routes/auth/electron-link'
import { Route as AuthDoneRouteImport } from './routes/auth/done'
import { Route as AuthActionRouteImport } from './routes/auth/action'
import { Route as AppAboutRouteImport } from './routes/_app/about'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkAccountRoute = AuthLinkAccountRouteImport.update({
  id: '/auth/link-account',
  path: '/auth/link-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthElectronLoginRoute = AuthElectronLoginRouteImport.update({
  id: '/auth/electron-login',
  path: '/auth/electron-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthElectronLinkRoute = AuthElectronLinkRouteImport.update({
  id: '/auth/electron-link',
  path: '/auth/electron-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDoneRoute = AuthDoneRouteImport.update({
  id: '/auth/done',
  path: '/auth/done',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActionRoute = AuthActionRouteImport.update({
  id: '/auth/action',
  path: '/auth/action',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/done': typeof AuthDoneRoute
  '/auth/electron-link': typeof AuthElectronLinkRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/done': typeof AuthDoneRoute
  '/auth/electron-link': typeof AuthElectronLinkRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/auth/action': typeof AuthActionRoute
  '/auth/done': typeof AuthDoneRoute
  '/auth/electron-link': typeof AuthElectronLinkRoute
  '/auth/electron-login': typeof AuthElectronLoginRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/link-account': typeof AuthLinkAccountRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/action'
    | '/auth/done'
    | '/auth/electron-link'
    | '/auth/electron-login'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/redirect'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/auth/action'
    | '/auth/done'
    | '/auth/electron-link'
    | '/auth/electron-login'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/redirect'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/auth/action'
    | '/auth/done'
    | '/auth/electron-link'
    | '/auth/electron-login'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/redirect'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthActionRoute: typeof AuthActionRoute
  AuthDoneRoute: typeof AuthDoneRoute
  AuthElectronLinkRoute: typeof AuthElectronLinkRoute
  AuthElectronLoginRoute: typeof AuthElectronLoginRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLinkAccountRoute: typeof AuthLinkAccountRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link-account': {
      id: '/auth/link-account'
      path: '/auth/link-account'
      fullPath: '/auth/link-account'
      preLoaderRoute: typeof AuthLinkAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/electron-login': {
      id: '/auth/electron-login'
      path: '/auth/electron-login'
      fullPath: '/auth/electron-login'
      preLoaderRoute: typeof AuthElectronLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/electron-link': {
      id: '/auth/electron-link'
      path: '/auth/electron-link'
      fullPath: '/auth/electron-link'
      preLoaderRoute: typeof AuthElectronLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/done': {
      id: '/auth/done'
      path: '/auth/done'
      fullPath: '/auth/done'
      preLoaderRoute: typeof AuthDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/action': {
      id: '/auth/action'
      path: '/auth/action'
      fullPath: '/auth/action'
      preLoaderRoute: typeof AuthActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthActionRoute: AuthActionRoute,
  AuthDoneRoute: AuthDoneRoute,
  AuthElectronLinkRoute: AuthElectronLinkRoute,
  AuthElectronLoginRoute: AuthElectronLoginRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLinkAccountRoute: AuthLinkAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRedirectRoute: AuthRedirectRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
