// Code generated by cmd/gen-permission-registry. DO NOT EDIT.
// Source: pivox.permission.v1 method options on every gRPC method.

package server

import (
	"github.com/dashkan/pivox/internal/permission"

	aiv1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/ai/v1"
	apiv1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/api/v1"
	assetsv1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/assets/v1"
	iamv1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/iam/v1"
	secretsv1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/secrets/v1"
	storagev1 "github.com/dashkan/pivox/internal/pkg/gen/pivox/storage/v1"
)

// GeneratedRegistry is the union permission registry for every
// gated gRPC method, derived from pivox.permission.v1 method
// options. Pass to PermissionInterceptor along with
// GeneratedExempt.
var GeneratedRegistry = Registry{
	"/pivox.ai.v1.AiChat/CreateConversation": {
		Permission: permission.AiConversationsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.CreateConversationRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/DeleteArtifact": {
		Permission: permission.AiConversationsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.DeleteArtifactRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/DeleteArtifactVersion": {
		Permission: permission.AiConversationsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.DeleteArtifactVersionRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/DeleteConversation": {
		Permission: permission.AiConversationsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.DeleteConversationRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/GenerateContent": {
		Permission: permission.AiChatStream,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.GenerateContentRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/GetArtifact": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.GetArtifactRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/GetArtifactVersion": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.GetArtifactVersionRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/GetConversation": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.GetConversationRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/GetMessage": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.GetMessageRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/ListArtifactVersions": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.ListArtifactVersionsRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/ListArtifacts": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.ListArtifactsRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/ListConversations": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.ListConversationsRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/ListMessages": {
		Permission: permission.AiConversationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.ListMessagesRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/StreamGenerateContent": {
		Permission: permission.AiChatStream,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*aiv1.GenerateContentRequest).GetParent())
		},
	},
	"/pivox.ai.v1.AiChat/SummarizeConversation": {
		Permission: permission.AiConversationsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*aiv1.SummarizeConversationRequest).GetName())
		},
	},
	"/pivox.ai.v1.AiChat/UpdateConversation": {
		Permission: permission.AiConversationsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("conversation.name", req.(*aiv1.UpdateConversationRequest).GetConversation().GetName())
		},
	},
	"/pivox.api.v1.ApiKeys/CreateKey": {
		Permission: permission.ApiKeysCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateKeyRequest).GetParent())
		},
	},
	"/pivox.api.v1.ApiKeys/DeleteKey": {
		Permission: permission.ApiKeysDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteKeyRequest).GetName())
		},
	},
	"/pivox.api.v1.ApiKeys/GetKey": {
		Permission: permission.ApiKeysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetKeyRequest).GetName())
		},
	},
	"/pivox.api.v1.ApiKeys/GetKeyString": {
		Permission: permission.ApiKeysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetKeyStringRequest).GetName())
		},
	},
	"/pivox.api.v1.ApiKeys/ListKeys": {
		Permission: permission.ApiKeysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListKeysRequest).GetParent())
		},
	},
	"/pivox.api.v1.ApiKeys/UndeleteKey": {
		Permission: permission.ApiKeysDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.UndeleteKeyRequest).GetName())
		},
	},
	"/pivox.api.v1.ApiKeys/UpdateKey": {
		Permission: permission.ApiKeysUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("key.name", req.(*apiv1.UpdateKeyRequest).GetKey().GetName())
		},
	},
	"/pivox.api.v1.Dashboards/CreateDashboard": {
		Permission: permission.DashboardsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateDashboardRequest).GetParent())
		},
	},
	"/pivox.api.v1.Dashboards/DeleteDashboard": {
		Permission: permission.DashboardsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteDashboardRequest).GetName())
		},
	},
	"/pivox.api.v1.Dashboards/GetDashboard": {
		Permission: permission.DashboardsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetDashboardRequest).GetName())
		},
	},
	"/pivox.api.v1.Dashboards/ListDashboards": {
		Permission: permission.DashboardsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListDashboardsRequest).GetParent())
		},
	},
	"/pivox.api.v1.Dashboards/QueryDashboardData": {
		Permission: permission.DashboardsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.QueryDashboardDataRequest).GetParent())
		},
	},
	"/pivox.api.v1.Dashboards/UpdateDashboard": {
		Permission: permission.DashboardsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("dashboard.name", req.(*apiv1.UpdateDashboardRequest).GetDashboard().GetName())
		},
	},
	"/pivox.api.v1.Organizations/CreateDomain": {
		Permission: permission.DomainsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateDomainRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/CreateInvitation": {
		Permission: permission.InvitationsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateInvitationRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/CreateMember": {
		Permission: permission.MembersCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.CreateMemberRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/DeleteDomain": {
		Permission: permission.DomainsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteDomainRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/DeleteInvitation": {
		Permission: permission.InvitationsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteInvitationRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/DeleteMember": {
		Permission: permission.MembersDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.DeleteMemberRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/DeleteOrganization": {
		Permission: permission.OrganizationsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteOrganizationRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/GetDomain": {
		Permission: permission.DomainsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetDomainRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/GetInvitationPolicy": {
		Permission: permission.InvitationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetInvitationPolicyRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/GetMember": {
		Permission: permission.MembersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.GetMemberRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/GetOrganization": {
		Permission: permission.OrganizationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetOrganizationRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/GetSsoConfig": {
		Permission: permission.OrganizationsSsoConfigRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetSsoConfigRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/ListDomains": {
		Permission: permission.DomainsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListDomainsRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/ListInvitations": {
		Permission: permission.InvitationsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListInvitationsRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/ListMembers": {
		Permission: permission.MembersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.ListMembersRequest).GetParent())
		},
	},
	"/pivox.api.v1.Organizations/TransferOwnership": {
		Permission: permission.OrganizationsTransferOwnership,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.TransferOwnershipRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/UndeleteOrganization": {
		Permission: permission.OrganizationsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.UndeleteOrganizationRequest).GetName())
		},
	},
	"/pivox.api.v1.Organizations/UpdateInvitationPolicy": {
		Permission: permission.InvitationsUpdatePolicy,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("invitation_policy.name", req.(*apiv1.UpdateInvitationPolicyRequest).GetInvitationPolicy().GetName())
		},
	},
	"/pivox.api.v1.Organizations/UpdateMember": {
		Permission: permission.MembersUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("member.name", req.(*iamv1.UpdateMemberRequest).GetMember().GetName())
		},
	},
	"/pivox.api.v1.Organizations/UpdateOrganization": {
		Permission: permission.OrganizationsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("organization.name", req.(*apiv1.UpdateOrganizationRequest).GetOrganization().GetName())
		},
	},
	"/pivox.api.v1.Organizations/UpdateSsoConfig": {
		Permission: permission.OrganizationsSsoConfigUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("sso_config.name", req.(*apiv1.UpdateSsoConfigRequest).GetSsoConfig().GetName())
		},
	},
	"/pivox.api.v1.Spaces/CreateMember": {
		Permission: permission.MembersCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.CreateMemberRequest).GetParent())
		},
	},
	"/pivox.api.v1.Spaces/CreateSpace": {
		Permission: permission.SpacesCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateSpaceRequest).GetParent())
		},
	},
	"/pivox.api.v1.Spaces/DeleteMember": {
		Permission: permission.MembersDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.DeleteMemberRequest).GetName())
		},
	},
	"/pivox.api.v1.Spaces/DeleteSpace": {
		Permission: permission.SpacesDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteSpaceRequest).GetName())
		},
	},
	"/pivox.api.v1.Spaces/GetMember": {
		Permission: permission.MembersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.GetMemberRequest).GetName())
		},
	},
	"/pivox.api.v1.Spaces/GetSpace": {
		Permission: permission.SpacesRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetSpaceRequest).GetName())
		},
	},
	"/pivox.api.v1.Spaces/ListMembers": {
		Permission: permission.MembersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.ListMembersRequest).GetParent())
		},
	},
	"/pivox.api.v1.Spaces/ListSpaces": {
		Permission: permission.SpacesRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListSpacesRequest).GetParent())
		},
	},
	"/pivox.api.v1.Spaces/UndeleteSpace": {
		Permission: permission.SpacesDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.UndeleteSpaceRequest).GetName())
		},
	},
	"/pivox.api.v1.Spaces/UpdateMember": {
		Permission: permission.MembersUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("member.name", req.(*iamv1.UpdateMemberRequest).GetMember().GetName())
		},
	},
	"/pivox.api.v1.Spaces/UpdateSpace": {
		Permission: permission.SpacesUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("space.name", req.(*apiv1.UpdateSpaceRequest).GetSpace().GetName())
		},
	},
	"/pivox.api.v1.TagBindings/CreateTagBinding": {
		Permission: permission.TagsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateTagBindingRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagBindings/DeleteTagBinding": {
		Permission: permission.TagsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteTagBindingRequest).GetName())
		},
	},
	"/pivox.api.v1.TagBindings/GetTagBinding": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetTagBindingRequest).GetName())
		},
	},
	"/pivox.api.v1.TagBindings/ListEffectiveTags": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListEffectiveTagsRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagBindings/ListTagBindings": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListTagBindingsRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagKeys/CreateTagKey": {
		Permission: permission.TagsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateTagKeyRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagKeys/DeleteTagKey": {
		Permission: permission.TagsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteTagKeyRequest).GetName())
		},
	},
	"/pivox.api.v1.TagKeys/GetTagKey": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetTagKeyRequest).GetName())
		},
	},
	"/pivox.api.v1.TagKeys/ListTagKeys": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListTagKeysRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagKeys/UpdateTagKey": {
		Permission: permission.TagsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("tag_key.name", req.(*apiv1.UpdateTagKeyRequest).GetTagKey().GetName())
		},
	},
	"/pivox.api.v1.TagValues/CreateTagValue": {
		Permission: permission.TagsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.CreateTagValueRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagValues/DeleteTagValue": {
		Permission: permission.TagsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.DeleteTagValueRequest).GetName())
		},
	},
	"/pivox.api.v1.TagValues/GetTagValue": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*apiv1.GetTagValueRequest).GetName())
		},
	},
	"/pivox.api.v1.TagValues/ListTagValues": {
		Permission: permission.TagsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*apiv1.ListTagValuesRequest).GetParent())
		},
	},
	"/pivox.api.v1.TagValues/UpdateTagValue": {
		Permission: permission.TagsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("tag_value.name", req.(*apiv1.UpdateTagValueRequest).GetTagValue().GetName())
		},
	},
	"/pivox.assets.v1.Assets/CreateAsset": {
		Permission: permission.AssetsAssetsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.CreateAssetRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Assets/CreateAssetVersion": {
		Permission: permission.AssetsAssetsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.CreateAssetVersionRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Assets/DeleteAsset": {
		Permission: permission.AssetsAssetsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.DeleteAssetRequest).GetName())
		},
	},
	"/pivox.assets.v1.Assets/GetAsset": {
		Permission: permission.AssetsAssetsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.GetAssetRequest).GetName())
		},
	},
	"/pivox.assets.v1.Assets/GetAssetMetadata": {
		Permission: permission.AssetsAssetsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.GetAssetMetadataRequest).GetName())
		},
	},
	"/pivox.assets.v1.Assets/GetAssetVersion": {
		Permission: permission.AssetsAssetsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.GetAssetVersionRequest).GetName())
		},
	},
	"/pivox.assets.v1.Assets/ImportAssets": {
		Permission: permission.AssetsAssetsImport,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.ImportAssetsRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Assets/ListAssetVersions": {
		Permission: permission.AssetsAssetsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.ListAssetVersionsRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Assets/ListAssets": {
		Permission: permission.AssetsAssetsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.ListAssetsRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Assets/UndeleteAsset": {
		Permission: permission.AssetsAssetsUndelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.UndeleteAssetRequest).GetName())
		},
	},
	"/pivox.assets.v1.Assets/UpdateAsset": {
		Permission: permission.AssetsAssetsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("asset.name", req.(*assetsv1.UpdateAssetRequest).GetAsset().GetName())
		},
	},
	"/pivox.assets.v1.Requests/ApproveRequest": {
		Permission: permission.AssetsRequestsApprove,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.ApproveRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/AssignRequest": {
		Permission: permission.AssetsRequestsAssign,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.AssignRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/CancelRequest": {
		Permission: permission.AssetsRequestsCancel,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.CancelRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/ClaimRequest": {
		Permission: permission.AssetsRequestsClaim,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.ClaimRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/CreateLineItem": {
		Permission: permission.AssetsLineItemsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.CreateLineItemRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Requests/CreateRequest": {
		Permission: permission.AssetsRequestsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.CreateRequestRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Requests/DeleteLineItem": {
		Permission: permission.AssetsLineItemsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.DeleteLineItemRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/DeleteRequest": {
		Permission: permission.AssetsRequestsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.DeleteRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/DeliverRequest": {
		Permission: permission.AssetsRequestsDeliver,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.DeliverRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/FulfillLineItem": {
		Permission: permission.AssetsLineItemsFulfill,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.FulfillLineItemRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/GetLineItem": {
		Permission: permission.AssetsLineItemsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.GetLineItemRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/GetRequest": {
		Permission: permission.AssetsRequestsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.GetRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/ListLineItems": {
		Permission: permission.AssetsLineItemsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.ListLineItemsRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Requests/ListRequests": {
		Permission: permission.AssetsRequestsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*assetsv1.ListRequestsRequest).GetParent())
		},
	},
	"/pivox.assets.v1.Requests/RejectRequest": {
		Permission: permission.AssetsRequestsReject,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.RejectRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/RequestRevision": {
		Permission: permission.AssetsRequestsApprove,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.RequestRevisionRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/SubmitRequest": {
		Permission: permission.AssetsRequestsSubmit,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*assetsv1.SubmitRequestRequest).GetName())
		},
	},
	"/pivox.assets.v1.Requests/UpdateLineItem": {
		Permission: permission.AssetsLineItemsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("line_item.name", req.(*assetsv1.UpdateLineItemRequest).GetLineItem().GetName())
		},
	},
	"/pivox.assets.v1.Requests/UpdateRequest": {
		Permission: permission.AssetsRequestsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("request.name", req.(*assetsv1.UpdateRequestRequest).GetRequest().GetName())
		},
	},
	"/pivox.iam.v1.Iam/AddGroupMembers": {
		Permission: permission.GroupsManageMembers,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("group", req.(*iamv1.AddGroupMembersRequest).GetGroup())
		},
	},
	"/pivox.iam.v1.Iam/CreateGroup": {
		Permission: permission.GroupsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.CreateGroupRequest).GetParent())
		},
	},
	"/pivox.iam.v1.Iam/DeleteGroup": {
		Permission: permission.GroupsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.DeleteGroupRequest).GetName())
		},
	},
	"/pivox.iam.v1.Iam/DeleteUser": {
		Permission: permission.UsersDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.DeleteUserRequest).GetName())
		},
	},
	"/pivox.iam.v1.Iam/GetGroup": {
		Permission: permission.GroupsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.GetGroupRequest).GetName())
		},
	},
	"/pivox.iam.v1.Iam/GetRole": {
		Permission: permission.RolesRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.GetRoleRequest).GetName())
		},
	},
	"/pivox.iam.v1.Iam/GetUser": {
		Permission: permission.UsersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*iamv1.GetUserRequest).GetName())
		},
	},
	"/pivox.iam.v1.Iam/ListGroupMembers": {
		Permission: permission.GroupsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("group", req.(*iamv1.ListGroupMembersRequest).GetGroup())
		},
	},
	"/pivox.iam.v1.Iam/ListGroups": {
		Permission: permission.GroupsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.ListGroupsRequest).GetParent())
		},
	},
	"/pivox.iam.v1.Iam/ListRoles": {
		Permission: permission.RolesRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.ListRolesRequest).GetParent())
		},
	},
	"/pivox.iam.v1.Iam/ListUsers": {
		Permission: permission.UsersRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*iamv1.ListUsersRequest).GetParent())
		},
	},
	"/pivox.iam.v1.Iam/RemoveGroupMembers": {
		Permission: permission.GroupsManageMembers,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("group", req.(*iamv1.RemoveGroupMembersRequest).GetGroup())
		},
	},
	"/pivox.iam.v1.Iam/UpdateGroup": {
		Permission: permission.GroupsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("group.name", req.(*iamv1.UpdateGroupRequest).GetGroup().GetName())
		},
	},
	"/pivox.secrets.v1.Secrets/CreateSecret": {
		Permission: permission.SecretsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*secretsv1.CreateSecretRequest).GetParent())
		},
	},
	"/pivox.secrets.v1.Secrets/DeleteSecret": {
		Permission: permission.SecretsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*secretsv1.DeleteSecretRequest).GetName())
		},
	},
	"/pivox.secrets.v1.Secrets/GetSecret": {
		Permission: permission.SecretsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*secretsv1.GetSecretRequest).GetName())
		},
	},
	"/pivox.secrets.v1.Secrets/ListSecrets": {
		Permission: permission.SecretsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*secretsv1.ListSecretsRequest).GetParent())
		},
	},
	"/pivox.secrets.v1.Secrets/UpdateSecret": {
		Permission: permission.SecretsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("secret.name", req.(*secretsv1.UpdateSecretRequest).GetSecret().GetName())
		},
	},
	"/pivox.storage.v1.Agents/DrainAgent": {
		Permission: permission.StorageAgentsDrain,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.DrainAgentRequest).GetName())
		},
	},
	"/pivox.storage.v1.Agents/GetAgent": {
		Permission: permission.StorageAgentsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.GetAgentRequest).GetName())
		},
	},
	"/pivox.storage.v1.Agents/ListAgents": {
		Permission: permission.StorageAgentsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*storagev1.ListAgentsRequest).GetParent())
		},
	},
	"/pivox.storage.v1.Agents/RemoveAgent": {
		Permission: permission.StorageAgentsRemove,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.RemoveAgentRequest).GetName())
		},
	},
	"/pivox.storage.v1.Endpoints/CreateEndpoint": {
		Permission: permission.StorageEndpointsCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*storagev1.CreateEndpointRequest).GetParent())
		},
	},
	"/pivox.storage.v1.Endpoints/DeleteEndpoint": {
		Permission: permission.StorageEndpointsDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.DeleteEndpointRequest).GetName())
		},
	},
	"/pivox.storage.v1.Endpoints/GetEndpoint": {
		Permission: permission.StorageEndpointsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.GetEndpointRequest).GetName())
		},
	},
	"/pivox.storage.v1.Endpoints/ListEndpoints": {
		Permission: permission.StorageEndpointsRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*storagev1.ListEndpointsRequest).GetParent())
		},
	},
	"/pivox.storage.v1.Endpoints/UpdateEndpoint": {
		Permission: permission.StorageEndpointsUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("endpoint.name", req.(*storagev1.UpdateEndpointRequest).GetEndpoint().GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/CreateStorageGateway": {
		Permission: permission.StorageGatewaysCreate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*storagev1.CreateStorageGatewayRequest).GetParent())
		},
	},
	"/pivox.storage.v1.StorageGateways/DeleteStorageGateway": {
		Permission: permission.StorageGatewaysDelete,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.DeleteStorageGatewayRequest).GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/GetInstallScript": {
		Permission: permission.StorageGatewaysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.GetInstallScriptRequest).GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/GetStorageGateway": {
		Permission: permission.StorageGatewaysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.GetStorageGatewayRequest).GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/GetUninstallScript": {
		Permission: permission.StorageGatewaysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.GetUninstallScriptRequest).GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/ListStorageGateways": {
		Permission: permission.StorageGatewaysRead,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("parent", req.(*storagev1.ListStorageGatewaysRequest).GetParent())
		},
	},
	"/pivox.storage.v1.StorageGateways/RotateRegistrationToken": {
		Permission: permission.StorageGatewaysUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.RotateRegistrationTokenRequest).GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/UpdateStorageGateway": {
		Permission: permission.StorageGatewaysUpdate,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("storage_gateway.name", req.(*storagev1.UpdateStorageGatewayRequest).GetStorageGateway().GetName())
		},
	},
	"/pivox.storage.v1.StorageGateways/UpgradeGateway": {
		Permission: permission.StorageGatewaysUpgrade,
		Extract: func(req any) (ScopeRef, error) {
			return ScopeFromPath("name", req.(*storagev1.UpgradeGatewayRequest).GetName())
		},
	},
}

// GeneratedExempt is the union exempt set for every gRPC method
// annotated `option (pivox.permission.v1.exempt) = true;`.
// Bootstrap RPCs (CreateOrganization etc.) and circular ones
// (TestIamPermissions) live here.
var GeneratedExempt = map[string]bool{
	"/pivox.api.v1.ApiKeys/LookupKey":                        true,
	"/pivox.api.v1.Organizations/AcceptInvitation":           true,
	"/pivox.api.v1.Organizations/CreateOrganization":         true,
	"/pivox.api.v1.Organizations/DeclineInvitation":          true,
	"/pivox.api.v1.Organizations/GetInvitation":              true,
	"/pivox.api.v1.Organizations/ListOrganizations":          true,
	"/pivox.api.v1.Organizations/TestIamPermissions":         true,
	"/pivox.api.v1.Spaces/TestIamPermissions":                true,
	"/pivox.iam.v1.Iam/DeleteAccount":                        true,
	"/pivox.iam.v1.Iam/ListAccountOrganizations":             true,
	"/pivox.iam.v1.Iam/ListPermissions":                      true,
	"/pivox.storage.v1.StorageGateways/CreateStorageSession": true,
}
