-- name: UpsertIdentity :one
-- Provisions / syncs a Keycloak-authenticated identity from a KC event
-- (keycloak-events topic). The row's `id` IS the Keycloak `sub` (passed in,
-- not generated by the uuidv7 default). REGISTER inserts; UPDATE_EMAIL /
-- UPDATE_PROFILE re-delivery updates. Idempotent.
--
-- display_name is overwritten only when the incoming value is non-empty:
-- REGISTER(broker) carries no name, so it must not blank an existing one
-- (set later by an UPDATE_PROFILE event or the token's name claim).
--
-- Soft-delete revival: a recycled sub (is_deleted=true row) means the same
-- principal is back — reset the tombstone rather than lock them out or write
-- new PII onto a row whose id the audit trail still references.
INSERT INTO identities (
    id,
    email,
    email_verified,
    display_name
) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    email          = EXCLUDED.email,
    email_verified = EXCLUDED.email_verified,
    display_name   = CASE WHEN EXCLUDED.display_name <> '' THEN EXCLUDED.display_name
                          ELSE identities.display_name END,
    is_deleted     = false,
    delete_time    = NULL,
    update_time    = now()
RETURNING *;

-- GetIdentityByEmail resolves a live identity (is_deleted=false) by
-- email. Returns ErrNoRows if no live identity has this email.
-- name: GetIdentityByEmail :one
SELECT * FROM identities WHERE email = $1 AND is_deleted = false;

-- GetIdentityByID looks up by primary key. Used by the DeleteAccount
-- LRO's DELETING_PIVOX_RECORDS phase to read the row before it is
-- soft-deleted. Returns soft-deleted rows too (callers like the audit
-- resolver need them to render is_deleted=true Actor placeholders).
-- name: GetIdentityByID :one
SELECT * FROM identities WHERE id = $1;

-- GetIdentitiesByIDs is the batched lookup used by the audit
-- resolver to inflate Actor messages on resource reads. The IDs are
-- typically a deduped slice of cache misses; row order is not
-- guaranteed and the caller should index results by id. Returns
-- soft-deleted rows so the resolver can flag is_deleted on the
-- returned Actor and blank PII.
-- name: GetIdentitiesByIDs :many
SELECT * FROM identities WHERE id = ANY(@ids::uuid[]);

-- SoftDeleteIdentity tombstones an identity: blanks PII, flips
-- is_deleted, stamps delete_time. The row is preserved so any
-- *_by audit field that points at this identity continues to
-- resolve (the audit resolver renders is_deleted=true with empty
-- PII rather than dropping the reference).
--
-- Returns the row's id so the caller can verify the UPDATE actually
-- landed. The predicate excludes already-soft-deleted rows so a
-- second call surfaces ErrNoRows — the caller is expected to
-- distinguish "real first-time tombstone" from "wrong ID / already
-- tombstoned" rather than silently no-op-and-continue (a wrong id
-- would otherwise let the LRO proceed to auth.DeleteUser with a
-- firebase_uid that doesn't belong to the row we thought we
-- deleted).
-- name: SoftDeleteIdentity :one
UPDATE identities SET
    is_deleted     = true,
    email          = '',
    display_name   = '',
    photo_url      = '',
    delete_time    = now(),
    update_time    = now()
WHERE id = $1 AND is_deleted = false
RETURNING id;
