/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AppRouteImport } from './routes/_app';
import { Route as AppIndexRouteImport } from './routes/_app/index';
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email';
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password';
import { Route as AuthRegisterRouteImport } from './routes/auth/register';
import { Route as AuthLoginRouteImport } from './routes/auth/login';
import { Route as AuthLinkAccountRouteImport } from './routes/auth/link-account';
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password';

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any);
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLinkAccountRoute = AuthLinkAccountRouteImport.update({
  id: '/auth/link-account',
  path: '/auth/link-account',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute;
  '/auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/auth/link-account': typeof AuthLinkAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/auth/register': typeof AuthRegisterRoute;
  '/auth/reset-password': typeof AuthResetPasswordRoute;
  '/auth/verify-email': typeof AuthVerifyEmailRoute;
}
export interface FileRoutesByTo {
  '/auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/auth/link-account': typeof AuthLinkAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/auth/register': typeof AuthRegisterRoute;
  '/auth/reset-password': typeof AuthResetPasswordRoute;
  '/auth/verify-email': typeof AuthVerifyEmailRoute;
  '/': typeof AppIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_app': typeof AppRouteWithChildren;
  '/auth/forgot-password': typeof AuthForgotPasswordRoute;
  '/auth/link-account': typeof AuthLinkAccountRoute;
  '/auth/login': typeof AuthLoginRoute;
  '/auth/register': typeof AuthRegisterRoute;
  '/auth/reset-password': typeof AuthResetPasswordRoute;
  '/auth/verify-email': typeof AuthVerifyEmailRoute;
  '/_app/': typeof AppIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/';
  id:
    | '__root__'
    | '/_app'
    | '/auth/forgot-password'
    | '/auth/link-account'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/_app/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute;
  AuthLinkAccountRoute: typeof AuthLinkAccountRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/': {
      id: '/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    '/auth/verify-email': {
      id: '/auth/verify-email';
      path: '/auth/verify-email';
      fullPath: '/auth/verify-email';
      preLoaderRoute: typeof AuthVerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/reset-password': {
      id: '/auth/reset-password';
      path: '/auth/reset-password';
      fullPath: '/auth/reset-password';
      preLoaderRoute: typeof AuthResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/register': {
      id: '/auth/register';
      path: '/auth/register';
      fullPath: '/auth/register';
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/login': {
      id: '/auth/login';
      path: '/auth/login';
      fullPath: '/auth/login';
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/link-account': {
      id: '/auth/link-account';
      path: '/auth/link-account';
      fullPath: '/auth/link-account';
      preLoaderRoute: typeof AuthLinkAccountRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auth/forgot-password': {
      id: '/auth/forgot-password';
      path: '/auth/forgot-password';
      fullPath: '/auth/forgot-password';
      preLoaderRoute: typeof AuthForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLinkAccountRoute: AuthLinkAccountRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
