// Permission generator. Reads internal/permission/permissions.yaml
// (the source of truth for the v1 permission catalog) and emits
// internal/permission/permissions_gen.go containing typed permission
// constants, the canonical `All` slice, and the `RoleGrants`
// role-to-permission grant data (which seeds the role_permissions
// table — the DB-side source of truth for authorization).
//
// Adding a permission:
//
//  1. Edit `internal/permission/permissions.yaml`.
//  2. Run `make generate` (or `go generate ./internal/permission/...`).
//  3. Use the new constant in handler code; the compile error from
//     referencing it before regeneration is your reminder.
//  4. Update the `INSERT INTO permissions` block in the init
//     migration to match — the drift-guard test
//     (TestPermissions_MigrationMatchesConstants) catches the
//     mismatch.
//
// The migration seed remains hand-maintained because golang-migrate
// doesn't support file-includes; keeping it in the same .sql file
// preserves single-step `make db-up` runs. Drift-guard is the safety
// net.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type permissionEntry struct {
	ID          string   `yaml:"id"`
	DisplayName string   `yaml:"display_name"`
	Description string   `yaml:"description"`
	Roles       []string `yaml:"roles"`
}

type permissionsFile struct {
	Permissions []permissionEntry `yaml:"permissions"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-permissions:", err)
		os.Exit(1)
	}
}

func run() error {
	// Paths are relative to the package directory containing the
	// //go:generate directive (internal/permission/), which is the CWD
	// `go generate` sets when invoking us.
	body, err := os.ReadFile("permissions.yaml")
	if err != nil {
		return fmt.Errorf("read yaml: %w", err)
	}
	var pf permissionsFile
	if err := yaml.Unmarshal(body, &pf); err != nil {
		return fmt.Errorf("parse yaml: %w", err)
	}
	if err := validate(pf); err != nil {
		return err
	}
	out := emitGo(pf)
	if err := os.WriteFile("permissions_gen.go", out, 0o644); err != nil {
		return fmt.Errorf("write generated: %w", err)
	}
	// Also emit the dev-seed grants so pre-seeded orgs (acme + dev orgs,
	// created via raw SQL, not the bootstrap path) get role_permissions
	// populated from the same source of truth. Path is relative to the
	// go:generate CWD (internal/permission/).
	seed := emitSeedSQL(pf)
	if err := os.WriteFile("../../scripts/seeds/16_role_permissions.sql", seed, 0o644); err != nil {
		return fmt.Errorf("write seed sql: %w", err)
	}
	return nil
}

// roleGrantPairs flattens permissions.yaml into ordered (role, permission_id)
// pairs — the shared source for both the Go RoleGrants map and the SQL seed.
func roleGrantPairs(pf permissionsFile) [][2]string {
	roleAllow := map[string][]string{"owner": {}, "admin": {}, "editor": {}, "viewer": {}}
	for _, p := range pf.Permissions {
		for _, r := range p.Roles {
			roleAllow[r] = append(roleAllow[r], p.ID)
		}
	}
	var pairs [][2]string
	for _, role := range []string{"owner", "admin", "editor", "viewer"} {
		ids := roleAllow[role]
		sort.Strings(ids)
		for _, id := range ids {
			pairs = append(pairs, [2]string{role, id})
		}
	}
	return pairs
}

// emitSeedSQL produces scripts/seeds/16_role_permissions.sql: a generic,
// idempotent INSERT that materializes the system-role grant matrix into
// role_permissions for every seeded system role, joining by role name.
func emitSeedSQL(pf permissionsFile) []byte {
	var b bytes.Buffer
	b.WriteString("-- Code generated by cmd/gen-permissions. DO NOT EDIT.\n")
	b.WriteString("-- Source: internal/permission/permissions.yaml\n--\n")
	b.WriteString("-- Materializes the static system-role grant matrix into\n")
	b.WriteString("-- role_permissions for every seeded system role (acme in\n")
	b.WriteString("-- 02_acme_sso.sql + the dev orgs in 12_dev_org_roles.sql), created\n")
	b.WriteString("-- via raw SQL rather than the CreateOrganization bootstrap path. So\n")
	b.WriteString("-- dev permission checks resolve in SQL exactly like app-created\n")
	b.WriteString("-- orgs. Must run after all role seeds; idempotent.\n--\n")
	b.WriteString("-- Runs inside the outer transaction from scripts/seed.sql.\n\n")
	b.WriteString("INSERT INTO role_permissions (role_id, permission_id)\n")
	b.WriteString("SELECT r.id, p.id\n")
	b.WriteString("  FROM roles r\n")
	b.WriteString("  JOIN (VALUES\n")
	pairs := roleGrantPairs(pf)
	for i, pr := range pairs {
		sep := ","
		if i == len(pairs)-1 {
			sep = ""
		}
		fmt.Fprintf(&b, "    ('%s', '%s')%s\n", pr[0], pr[1], sep)
	}
	b.WriteString("  ) AS g(role_name, permission_id)\n")
	b.WriteString("    ON g.role_name = r.name AND r.is_system = true\n")
	b.WriteString("  JOIN permissions p ON p.permission_id = g.permission_id\n")
	b.WriteString("ON CONFLICT (role_id, permission_id) DO NOTHING;\n")
	return b.Bytes()
}

// validate enforces YAML invariants: unique ids, non-empty fields,
// known role names.
func validate(pf permissionsFile) error {
	knownRoles := map[string]bool{
		"owner": true, "admin": true, "editor": true, "viewer": true,
	}
	seen := map[string]bool{}
	for _, p := range pf.Permissions {
		if p.ID == "" || p.DisplayName == "" || p.Description == "" {
			return fmt.Errorf("permission %q: id/display_name/description must be non-empty", p.ID)
		}
		if seen[p.ID] {
			return fmt.Errorf("duplicate permission id %q", p.ID)
		}
		seen[p.ID] = true
		if len(p.Roles) == 0 {
			return fmt.Errorf("permission %q: roles list empty (no role grants it — handler checks would always deny)", p.ID)
		}
		for _, r := range p.Roles {
			if !knownRoles[r] {
				return fmt.Errorf("permission %q: unknown role %q", p.ID, r)
			}
		}
	}
	return nil
}

// constName converts a dot-id like "assets.lineItems.fulfill" to a
// Go camelcase identifier "AssetsLineItemsFulfill".
func constName(id string) string {
	parts := strings.Split(id, ".")
	out := strings.Builder{}
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		out.WriteString(strings.ToUpper(p[:1]))
		out.WriteString(p[1:])
	}
	return out.String()
}

// emitGo produces the Go source for permissions_gen.go.
func emitGo(pf permissionsFile) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-permissions. DO NOT EDIT.\n")
	b.WriteString("// Source: internal/permission/permissions.yaml\n\n")
	b.WriteString("package permission\n\n")
	b.WriteString("// Typed permission constants. Source of truth: permissions.yaml.\n")
	b.WriteString("const (\n")
	for _, p := range pf.Permissions {
		fmt.Fprintf(&b, "\t%s = %q\n", constName(p.ID), p.ID)
	}
	b.WriteString(")\n\n")

	b.WriteString("// All is the canonical, ordered list of every permission_id known\n")
	b.WriteString("// to the v1 system. Order matches the YAML for stable downstream\n")
	b.WriteString("// output.\n")
	b.WriteString("var All = []string{\n")
	for _, p := range pf.Permissions {
		fmt.Fprintf(&b, "\t%s,\n", constName(p.ID))
	}
	b.WriteString("}\n\n")

	roleAllow := map[string][]string{
		"owner": {}, "admin": {}, "editor": {}, "viewer": {},
	}
	for _, p := range pf.Permissions {
		for _, r := range p.Roles {
			roleAllow[r] = append(roleAllow[r], p.ID)
		}
	}
	roleOrder := []string{"owner", "admin", "editor", "viewer"}
	b.WriteString("// RoleGrants is the role-to-permission grant data, in ordered-slice\n")
	b.WriteString("// form keyed by role name. Each role's set is the union of every\n")
	b.WriteString("// permission whose `roles:` list mentions that role name in\n")
	b.WriteString("// permissions.yaml. It seeds the role_permissions table (per-org\n")
	b.WriteString("// system-role grants) at org bootstrap and in the dev seed, so\n")
	b.WriteString("// permission checks resolve in SQL — the DB-side source of truth\n")
	b.WriteString("// for authorization.\n")
	b.WriteString("var RoleGrants = map[string][]string{\n")
	for _, role := range roleOrder {
		fmt.Fprintf(&b, "\tRole%s: {\n", strings.ToUpper(role[:1])+role[1:])
		ids := roleAllow[role]
		sort.Strings(ids)
		for _, id := range ids {
			fmt.Fprintf(&b, "\t\t%s,\n", constName(id))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated Go: %w\n---\n%s", err, b.String()))
	}
	return formatted
}
