// Permission generator. Reads internal/permission/permissions.yaml
// (the source of truth for the v1 permission catalog) and emits
// internal/permission/permissions_gen.go containing typed permission
// constants, the canonical `All` slice, and the role-to-permission
// grant matrix.
//
// Adding a permission:
//
//  1. Edit `internal/permission/permissions.yaml`.
//  2. Run `make generate` (or `go generate ./internal/permission/...`).
//  3. Use the new constant in handler code; the compile error from
//     referencing it before regeneration is your reminder.
//  4. Update the `INSERT INTO permissions` block in the init
//     migration to match — the drift-guard test
//     (TestPermissions_MigrationMatchesConstants) catches the
//     mismatch.
//
// The migration seed remains hand-maintained because golang-migrate
// doesn't support file-includes; keeping it in the same .sql file
// preserves single-step `make db-up` runs. Drift-guard is the safety
// net.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type permissionEntry struct {
	ID          string   `yaml:"id"`
	DisplayName string   `yaml:"display_name"`
	Description string   `yaml:"description"`
	Roles       []string `yaml:"roles"`
}

type permissionsFile struct {
	Permissions []permissionEntry `yaml:"permissions"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-permissions:", err)
		os.Exit(1)
	}
}

func run() error {
	// Paths are relative to the package directory containing the
	// //go:generate directive (internal/permission/), which is the CWD
	// `go generate` sets when invoking us.
	body, err := os.ReadFile("permissions.yaml")
	if err != nil {
		return fmt.Errorf("read yaml: %w", err)
	}
	var pf permissionsFile
	if err := yaml.Unmarshal(body, &pf); err != nil {
		return fmt.Errorf("parse yaml: %w", err)
	}
	if err := validate(pf); err != nil {
		return err
	}
	out := emitGo(pf)
	if err := os.WriteFile("permissions_gen.go", out, 0o644); err != nil {
		return fmt.Errorf("write generated: %w", err)
	}
	return nil
}

// validate enforces YAML invariants: unique ids, non-empty fields,
// known role names.
func validate(pf permissionsFile) error {
	knownRoles := map[string]bool{
		"owner": true, "admin": true, "editor": true, "viewer": true,
	}
	seen := map[string]bool{}
	for _, p := range pf.Permissions {
		if p.ID == "" || p.DisplayName == "" || p.Description == "" {
			return fmt.Errorf("permission %q: id/display_name/description must be non-empty", p.ID)
		}
		if seen[p.ID] {
			return fmt.Errorf("duplicate permission id %q", p.ID)
		}
		seen[p.ID] = true
		if len(p.Roles) == 0 {
			return fmt.Errorf("permission %q: roles list empty (no role grants it — handler checks would always deny)", p.ID)
		}
		for _, r := range p.Roles {
			if !knownRoles[r] {
				return fmt.Errorf("permission %q: unknown role %q", p.ID, r)
			}
		}
	}
	return nil
}

// constName converts a dot-id like "assets.lineItems.fulfill" to a
// Go camelcase identifier "AssetsLineItemsFulfill".
func constName(id string) string {
	parts := strings.Split(id, ".")
	out := strings.Builder{}
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		out.WriteString(strings.ToUpper(p[:1]))
		out.WriteString(p[1:])
	}
	return out.String()
}

// emitGo produces the Go source for permissions_gen.go.
func emitGo(pf permissionsFile) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/gen-permissions. DO NOT EDIT.\n")
	b.WriteString("// Source: internal/permission/permissions.yaml\n\n")
	b.WriteString("package permission\n\n")
	b.WriteString("// Typed permission constants. Source of truth: permissions.yaml.\n")
	b.WriteString("const (\n")
	for _, p := range pf.Permissions {
		fmt.Fprintf(&b, "\t%s = %q\n", constName(p.ID), p.ID)
	}
	b.WriteString(")\n\n")

	b.WriteString("// All is the canonical, ordered list of every permission_id known\n")
	b.WriteString("// to the v1 system. Order matches the YAML for stable downstream\n")
	b.WriteString("// output.\n")
	b.WriteString("var All = []string{\n")
	for _, p := range pf.Permissions {
		fmt.Fprintf(&b, "\t%s,\n", constName(p.ID))
	}
	b.WriteString("}\n\n")

	roleAllow := map[string][]string{
		"owner": {}, "admin": {}, "editor": {}, "viewer": {},
	}
	for _, p := range pf.Permissions {
		for _, r := range p.Roles {
			roleAllow[r] = append(roleAllow[r], p.ID)
		}
	}
	roleOrder := []string{"owner", "admin", "editor", "viewer"}
	b.WriteString("// matrix is the role-to-permission grant map. Each role's set is\n")
	b.WriteString("// the union of every permission whose `roles:` list mentions that\n")
	b.WriteString("// role name in permissions.yaml.\n")
	b.WriteString("var matrix = map[string]map[string]bool{\n")
	for _, role := range roleOrder {
		fmt.Fprintf(&b, "\tRole%s: {\n", strings.ToUpper(role[:1])+role[1:])
		ids := roleAllow[role]
		sort.Strings(ids)
		for _, id := range ids {
			fmt.Fprintf(&b, "\t\t%s: true,\n", constName(id))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		panic(fmt.Errorf("format generated Go: %w\n---\n%s", err, b.String()))
	}
	return formatted
}
