-- Track whether the conversation title was set by the user (vs. auto-
-- generated by the summarization path). Used by `:summarize` to skip
-- regeneration on conversations the user has manually titled.
ALTER TABLE ai_conversations
    ADD COLUMN title_user_set BOOLEAN NOT NULL DEFAULT FALSE;
