// protoc-gen-pivox-cpp-bridge
//
// Emits the C++ bridge for each service: per-RPC Apple bridge methods
// that accept Swift-origin proto pointers (via OpaquePointer from Swift)
// and either return a Swift-origin `google.rpc.Status` by value (unary)
// or invoke C fn-ptr callbacks with Swift-origin pointer args
// (server-streaming).
//
// Output shape:
//
//	<service>_bridge.h.inc  — included inside `ChatClient`'s class body,
//	                           contributes method DECLARATIONS per RPC.
//	<service>_bridge.cc.inc — included in the translation unit that
//	                           defines `ChatClient`, contributes method
//	                           IMPLEMENTATIONS.
//
// The hand-written ChatClient shell (lifecycle, SWIFT_SHARED_REFERENCE,
// channel/stub management, StreamReactor) pulls these in with `#include`
// under an `#if defined(__APPLE__)` guard. The generated side is pure
// boilerplate: one pattern per unary RPC, one per server-streaming RPC.
//
// Retirement trigger: Swift-C++ interop supports passing Swift-origin
// types to C++ function parameters AND receiving them in callbacks
// without OpaquePointer erasure. At that point the Apple bridge layer
// becomes a thin inline wrapper (or disappears entirely) and WinRT uses
// ChatClientCore directly.
package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/dashkan/pivox/tools/internal/pivoxgen"
)

func main() {
	var flags flag.FlagSet
	var opts pivoxgen.CommonOptions
	pivoxgen.RegisterCommonFlags(&flags, &opts)

	protogen.Options{ParamFunc: flags.Set}.Run(func(p *protogen.Plugin) error {
		pivoxgen.SetSupportedFeatures(p)

		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			if len(f.Services) == 0 {
				continue
			}
			for _, svc := range f.Services {
				if !pivoxgen.ShouldGenerateService(&opts, string(svc.Desc.FullName())) {
					continue
				}
				if err := emitService(p, svc); err != nil {
					return fmt.Errorf("%s: %w", svc.Desc.FullName(), err)
				}
			}
		}
		return nil
	})
}

// emitService writes the .h.inc and .cc.inc pair for one service. Each
// RPC becomes one method on the hand-written ChatClient class.
func emitService(p *protogen.Plugin, svc *protogen.Service) error {
	base := lowerSnake(string(svc.Desc.Name()))

	if err := emitHeaderInc(p, svc, base); err != nil {
		return err
	}
	if err := emitImplInc(p, svc, base); err != nil {
		return err
	}
	return nil
}

func emitHeaderInc(p *protogen.Plugin, svc *protogen.Service, base string) error {
	name := fmt.Sprintf("%s_bridge.h.inc", base)
	g := p.NewGeneratedFile(name, "")

	g.P("// Generated by protoc-gen-pivox-cpp-bridge. DO NOT EDIT.")
	g.P("// service: ", svc.Desc.FullName())
	g.P("//")
	g.P("// Declarations of per-RPC Apple bridge methods. Include INSIDE the")
	g.P("// ChatClient class body, guarded by #if defined(__APPLE__).")
	g.P()

	// UnaryStatus is declared at namespace scope in chat_client.h (hand-
	// written). Returning it by value from bridge methods works across
	// Swift-C++ interop; a Swift-origin type (e.g. google.rpc.Status)
	// does NOT — Swift marks such methods "unavailable" because their
	// return type resolves unavailable in Swift for instance members.
	// Verified empirically in Swift 6.3.
	for _, m := range svc.Methods {
		if !shouldEmit(m) {
			g.P("// ", m.Desc.FullName(), " — skipped: input/output type lives outside PivoxModels")
			g.P()
			continue
		}
		g.P("// ", m.Desc.FullName())
		switch rpcKindOf(m) {
		case rpcUnary:
			emitUnaryDecl(g, m)
		case rpcServerStream:
			emitStreamDecl(g, m)
		case rpcClientStream, rpcBidi:
			g.P("// TODO(bidi-gen): ", rpcKindOf(m), " not yet supported by")
			g.P("//   protoc-gen-pivox-cpp-bridge. When a real bidi/client-stream RPC")
			g.P("//   is added, extend cpp-bridge's `emitStreamDecl`/`emitStreamImpl`")
			g.P("//   to emit a bidi-capable handle API (send/close/cancel) backed by")
			g.P("//   a ClientBidiReactor that does not auto-half-close after the")
			g.P("//   first write. The Swift facade needs a matching shape (e.g. a")
			g.P("//   send(request) method alongside the AsyncThrowingStream).")
		}
		g.P()
	}
	return nil
}

// rpcKind is the coarse-grained shape of an RPC.
type rpcKind int

const (
	rpcUnary rpcKind = iota
	rpcServerStream
	rpcClientStream
	rpcBidi
)

func (k rpcKind) String() string {
	switch k {
	case rpcUnary:
		return "unary"
	case rpcServerStream:
		return "server-stream"
	case rpcClientStream:
		return "client-stream"
	case rpcBidi:
		return "bidi"
	}
	return "unknown"
}

func rpcKindOf(m *protogen.Method) rpcKind {
	cs := m.Desc.IsStreamingClient()
	ss := m.Desc.IsStreamingServer()
	switch {
	case cs && ss:
		return rpcBidi
	case cs:
		return rpcClientStream
	case ss:
		return rpcServerStream
	default:
		return rpcUnary
	}
}

// shouldEmit returns true iff both input and output message types are
// in a proto package we emit `parse(fromBytes:)` extensions for in
// PivoxModels (i.e. NOT in the SwiftProtobuf-provided `google.protobuf.*`
// namespace). `DeleteConversation` → `google.protobuf.Empty` fails this
// check today; add SwiftProtobuf-side extensions to re-enable.
func shouldEmit(m *protogen.Method) bool {
	return pkgIsPivoxModels(m.Input) && pkgIsPivoxModels(m.Output)
}

func pkgIsPivoxModels(msg *protogen.Message) bool {
	pkg := string(msg.Desc.ParentFile().Package())
	return !strings.HasPrefix(pkg, "google.protobuf")
}

func emitImplInc(p *protogen.Plugin, svc *protogen.Service, base string) error {
	name := fmt.Sprintf("%s_bridge.cc.inc", base)
	g := p.NewGeneratedFile(name, "")

	g.P("// Generated by protoc-gen-pivox-cpp-bridge. DO NOT EDIT.")
	g.P("// service: ", svc.Desc.FullName())
	g.P("//")
	g.P("// Method implementations. Include in the translation unit that")
	g.P("// defines ChatClient, guarded by #if defined(__APPLE__).")
	g.P("// Assumes the surrounding TU provides:")
	g.P("//   - `SwiftArrayToVector(swift::Array<uint8_t>) -> std::vector<uint8_t>`")
	g.P("//   - `StartStreamBytes(...)` and `DoUnaryCall(...)` transport helpers")
	g.P("//     on ChatClient (or a shared base).")
	g.P()

	for _, m := range svc.Methods {
		if !shouldEmit(m) {
			continue
		}
		g.P("// ", m.Desc.FullName())
		switch rpcKindOf(m) {
		case rpcUnary:
			emitUnaryImpl(g, m)
		case rpcServerStream:
			emitStreamImpl(g, m)
		case rpcClientStream, rpcBidi:
			// Decl-side emits the TODO stub; no impl needed.
		}
		g.P()
	}
	return nil
}

// emitUnaryDecl writes the Apple bridge signature for a unary RPC.
//
//	UnaryStatus ListMessages(
//	    const PivoxModels::Pivox_Ai_V1_ListMessagesRequest* request,
//	    PivoxModels::Pivox_Ai_V1_ListMessagesResponse* response_out);
func emitUnaryDecl(g *protogen.GeneratedFile, m *protogen.Method) {
	reqT := swiftQualifiedTypeName(m.Input)
	respT := swiftQualifiedTypeName(m.Output)
	g.P("UnaryStatus ", m.GoName, "(")
	g.P("    const ", reqT, "* request,")
	g.P("    ", respT, "* response_out);")
}

// emitUnaryImpl writes the definition:
//   - extract Swift bytes
//   - parse into native C++ proto via the grpc-cpp generated stub
//   - serialize response → construct Swift proto
//   - return status as Swift google.rpc.Status
func emitUnaryImpl(g *protogen.GeneratedFile, m *protogen.Method) {
	reqT := swiftQualifiedTypeName(m.Input)
	respT := swiftQualifiedTypeName(m.Output)
	cppMethodPath := fmt.Sprintf("/%s/%s",
		m.Parent.Desc.FullName(), m.Desc.Name())

	g.P("UnaryStatus ChatClient::", m.GoName, "(")
	g.P("    const ", reqT, "* request,")
	g.P("    ", respT, "* response_out) {")
	g.P("  if (!request || !response_out) {")
	g.P("    return UnaryStatus{3 /* INVALID_ARGUMENT */, \"null request or response_out\"};")
	g.P("  }")
	g.P()
	g.P("  auto req_bytes = SwiftArrayToVector(request->serializedBytesArray());")
	g.P("  std::vector<uint8_t> resp_bytes;")
	g.P("  auto status = DoUnaryCall(\"", cppMethodPath, "\",")
	g.P("      req_bytes.data(), req_bytes.size(), &resp_bytes);")
	g.P()
	g.P("  if (!status.ok()) {")
	g.P("    return UnaryStatus{static_cast<int32_t>(status.error_code()), status.error_message()};")
	g.P("  }")
	g.P()
	g.P("  auto arr = swift::Array<uint8_t>::init();")
	g.P("  for (auto b : resp_bytes) arr.append(b);")
	g.P("  *response_out = ", respT, "::parse(arr);")
	g.P("  return UnaryStatus{0, std::string{}};")
	g.P("}")
}

// emitStreamDecl writes the Apple bridge signature for a server-streaming RPC.
//
//	void Stream(
//	    const PivoxModels::Pivox_Ai_V1_ClientEvent* request,
//	    void* ctx,
//	    void (*on_event)(void* ctx, const PivoxModels::Pivox_Ai_V1_ServerEvent* event),
//	    void (*on_error)(void* ctx, int32_t code, const char* message),
//	    void (*on_complete)(void* ctx));
func emitStreamDecl(g *protogen.GeneratedFile, m *protogen.Method) {
	reqT := swiftQualifiedTypeName(m.Input)
	respT := swiftQualifiedTypeName(m.Output)
	g.P("void ", m.GoName, "(")
	g.P("    const ", reqT, "* request,")
	g.P("    void* ctx,")
	g.P("    void (*on_event)(void* ctx, const ", respT, "* event),")
	g.P("    void (*on_error)(void* ctx, int32_t code, const char* message),")
	g.P("    void (*on_complete)(void* ctx));")
}

func emitStreamImpl(g *protogen.GeneratedFile, m *protogen.Method) {
	reqT := swiftQualifiedTypeName(m.Input)
	respT := swiftQualifiedTypeName(m.Output)
	cppMethodPath := fmt.Sprintf("/%s/%s",
		m.Parent.Desc.FullName(), m.Desc.Name())
	_ = cppMethodPath // StreamReactor internally uses the hard-coded path

	g.P("void ChatClient::", m.GoName, "(")
	g.P("    const ", reqT, "* request,")
	g.P("    void* ctx,")
	g.P("    void (*on_event)(void* ctx, const ", respT, "* event),")
	g.P("    void (*on_error)(void* ctx, int32_t code, const char* message),")
	g.P("    void (*on_complete)(void* ctx)) {")
	g.P("  if (!request) {")
	g.P("    if (on_error) on_error(ctx, 3 /* INVALID_ARGUMENT */, \"null request\");")
	g.P("    return;")
	g.P("  }")
	g.P("  auto bytes = SwiftArrayToVector(request->serializedBytesArray());")
	g.P("  StartStreamBytes(")
	g.P("      bytes.data(), bytes.size(),")
	g.P("      [ctx, on_event](const uint8_t* bs, size_t n) {")
	g.P("        if (!on_event) return;")
	g.P("        auto arr = swift::Array<uint8_t>::init();")
	g.P("        for (size_t i = 0; i < n; ++i) arr.append(bs[i]);")
	g.P("        auto ev = ", respT, "::parse(arr);")
	g.P("        on_event(ctx, &ev);")
	g.P("      },")
	g.P("      [ctx, on_error](const std::string& msg) {")
	g.P("        if (on_error) on_error(ctx, 2 /* UNKNOWN */, msg.c_str());")
	g.P("      },")
	g.P("      [ctx, on_complete]() {")
	g.P("        if (on_complete) on_complete(ctx);")
	g.P("      });")
	g.P("}")
}

// swiftQualifiedTypeName produces `PivoxModels::Pivox_Ai_V1_ListMessagesRequest`
// from a proto Message. Matches the type projection that swift-protobuf
// + Swift-C++ interop expose.
func swiftQualifiedTypeName(m *protogen.Message) string {
	pkg := string(m.Desc.ParentFile().Package())
	parts := splitDot(pkg)
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = upperFirst(p)
	}
	prefix := joinUnderscore(parts)
	if prefix != "" {
		prefix += "_"
	}
	return "PivoxModels::" + prefix + string(m.Desc.Name())
}

// --- tiny string helpers ---

func lowerSnake(s string) string {
	var out []byte
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				out = append(out, '_')
			}
			out = append(out, byte(r-'A'+'a'))
			continue
		}
		out = append(out, byte(r))
	}
	return string(out)
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	if s[0] >= 'a' && s[0] <= 'z' {
		return string(s[0]-'a'+'A') + s[1:]
	}
	return s
}

func splitDot(s string) []string {
	if s == "" {
		return nil
	}
	var out []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '.' {
			out = append(out, s[start:i])
			start = i + 1
		}
	}
	out = append(out, s[start:])
	return out
}

func joinUnderscore(parts []string) string {
	var out string
	for i, p := range parts {
		if i > 0 {
			out += "_"
		}
		out += p
	}
	return out
}
