import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig, mergeConfig } from "vitest/config";
import { tanstackViteConfig } from "@tanstack/vite-config";
import packageJson from "./package.json";

const config = defineConfig({
  plugins: [tailwindcss()],
  build: {
    rollupOptions: {
      onwarn(warning, warn) {
        if (warning.code === "MODULE_LEVEL_DIRECTIVE") return;
        if (warning.code === "SOURCEMAP_ERROR") return;
        warn(warning);
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  test: {
    name: packageJson.name,
    dir: "./",
    watch: false,
    globals: true,
    environment: "node",
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov"],
      exclude: [
        "node_modules/",
        "dist/",
        "tests/",
        "**/*.test.ts",
        "**/*.config.ts",
        "**/types.ts",
      ],
      include: ["src/**/*.ts"],
    },
  },
});

export default mergeConfig(
  config,
  tanstackViteConfig({
    entry: [
      "./src/index.ts",
      // hooks
      "./src/shadcn/hooks/use-mobile.ts",
      // lib
      "./src/shadcn/lib/utils.ts",
      // ai-elements
      "./src/vercel/ai-elements/agent.tsx",
      "./src/vercel/ai-elements/artifact.tsx",
      "./src/vercel/ai-elements/attachments.tsx",
      "./src/vercel/ai-elements/audio-player.tsx",
      "./src/vercel/ai-elements/canvas.tsx",
      "./src/vercel/ai-elements/chain-of-thought.tsx",
      "./src/vercel/ai-elements/checkpoint.tsx",
      "./src/vercel/ai-elements/code-block.tsx",
      "./src/vercel/ai-elements/commit.tsx",
      "./src/vercel/ai-elements/confirmation.tsx",
      "./src/vercel/ai-elements/connection.tsx",
      "./src/vercel/ai-elements/context.tsx",
      "./src/vercel/ai-elements/controls.tsx",
      "./src/vercel/ai-elements/conversation.tsx",
      "./src/vercel/ai-elements/edge.tsx",
      "./src/vercel/ai-elements/environment-variables.tsx",
      "./src/vercel/ai-elements/file-tree.tsx",
      "./src/vercel/ai-elements/image.tsx",
      "./src/vercel/ai-elements/inline-citation.tsx",
      "./src/vercel/ai-elements/jsx-preview.tsx",
      "./src/vercel/ai-elements/message.tsx",
      "./src/vercel/ai-elements/mic-selector.tsx",
      "./src/vercel/ai-elements/model-selector.tsx",
      "./src/vercel/ai-elements/node.tsx",
      "./src/vercel/ai-elements/open-in-chat.tsx",
      "./src/vercel/ai-elements/package-info.tsx",
      "./src/vercel/ai-elements/panel.tsx",
      "./src/vercel/ai-elements/persona.tsx",
      "./src/vercel/ai-elements/plan.tsx",
      "./src/vercel/ai-elements/prompt-input.tsx",
      "./src/vercel/ai-elements/queue.tsx",
      "./src/vercel/ai-elements/reasoning.tsx",
      "./src/vercel/ai-elements/sandbox.tsx",
      "./src/vercel/ai-elements/schema-display.tsx",
      "./src/vercel/ai-elements/shimmer.tsx",
      "./src/vercel/ai-elements/snippet.tsx",
      "./src/vercel/ai-elements/sources.tsx",
      "./src/vercel/ai-elements/speech-input.tsx",
      "./src/vercel/ai-elements/stack-trace.tsx",
      "./src/vercel/ai-elements/suggestion.tsx",
      "./src/vercel/ai-elements/task.tsx",
      "./src/vercel/ai-elements/terminal.tsx",
      "./src/vercel/ai-elements/test-results.tsx",
      "./src/vercel/ai-elements/tool.tsx",
      "./src/vercel/ai-elements/toolbar.tsx",
      "./src/vercel/ai-elements/transcription.tsx",
      "./src/vercel/ai-elements/voice-selector.tsx",
      "./src/vercel/ai-elements/web-preview.tsx",
      // shadcn ui
      "./src/shadcn/components/ui/accordion.tsx",
      "./src/shadcn/components/ui/alert.tsx",
      "./src/shadcn/components/ui/alert-dialog.tsx",
      "./src/shadcn/components/ui/aspect-ratio.tsx",
      "./src/shadcn/components/ui/avatar.tsx",
      "./src/shadcn/components/ui/badge.tsx",
      "./src/shadcn/components/ui/breadcrumb.tsx",
      "./src/shadcn/components/ui/button.tsx",
      "./src/shadcn/components/ui/button-group.tsx",
      "./src/shadcn/components/ui/calendar.tsx",
      "./src/shadcn/components/ui/card.tsx",
      "./src/shadcn/components/ui/carousel.tsx",
      "./src/shadcn/components/ui/chart.tsx",
      "./src/shadcn/components/ui/checkbox.tsx",
      "./src/shadcn/components/ui/collapsible.tsx",
      "./src/shadcn/components/ui/combobox.tsx",
      "./src/shadcn/components/ui/command.tsx",
      "./src/shadcn/components/ui/context-menu.tsx",
      "./src/shadcn/components/ui/dialog.tsx",
      "./src/shadcn/components/ui/direction.tsx",
      "./src/shadcn/components/ui/drawer.tsx",
      "./src/shadcn/components/ui/dropdown-menu.tsx",
      "./src/shadcn/components/ui/empty.tsx",
      "./src/shadcn/components/ui/field.tsx",
      "./src/shadcn/components/ui/hover-card.tsx",
      "./src/shadcn/components/ui/input.tsx",
      "./src/shadcn/components/ui/input-group.tsx",
      "./src/shadcn/components/ui/input-otp.tsx",
      "./src/shadcn/components/ui/item.tsx",
      "./src/shadcn/components/ui/kbd.tsx",
      "./src/shadcn/components/ui/label.tsx",
      "./src/shadcn/components/ui/menubar.tsx",
      "./src/shadcn/components/ui/native-select.tsx",
      "./src/shadcn/components/ui/navigation-menu.tsx",
      "./src/shadcn/components/ui/pagination.tsx",
      "./src/shadcn/components/ui/popover.tsx",
      "./src/shadcn/components/ui/progress.tsx",
      "./src/shadcn/components/ui/radio-group.tsx",
      "./src/shadcn/components/ui/resizable.tsx",
      "./src/shadcn/components/ui/scroll-area.tsx",
      "./src/shadcn/components/ui/select.tsx",
      "./src/shadcn/components/ui/separator.tsx",
      "./src/shadcn/components/ui/sheet.tsx",
      "./src/shadcn/components/ui/sidebar.tsx",
      "./src/shadcn/components/ui/skeleton.tsx",
      "./src/shadcn/components/ui/slider.tsx",
      "./src/shadcn/components/ui/sonner.tsx",
      "./src/shadcn/components/ui/spinner.tsx",
      "./src/shadcn/components/ui/switch.tsx",
      "./src/shadcn/components/ui/table.tsx",
      "./src/shadcn/components/ui/tabs.tsx",
      "./src/shadcn/components/ui/textarea.tsx",
      "./src/shadcn/components/ui/toggle.tsx",
      "./src/shadcn/components/ui/toggle-group.tsx",
      "./src/shadcn/components/ui/tooltip.tsx",
    ],
    srcDir: "./src",
    cjs: false,
  }),
);
