#ifndef PIVOX_AI_CHAT_CLIENT_H
#define PIVOX_AI_CHAT_CLIENT_H

#include <atomic>
#include <cstdint>
#include <condition_variable>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

#include <grpcpp/grpcpp.h>
#include <grpcpp/generic/generic_stub.h>

// Swift↔C++ interop annotation macros.
#if __has_include(<swift/bridging>)
#include <swift/bridging>
#else
#define SWIFT_SHARED_REFERENCE(retain, release)
#endif

// On Apple, pull in the Swift-emitted C++ header so the client can
// accept/return Swift-originated proto types directly.
#if defined(__APPLE__) && __has_include("PivoxModels-Swift.h")
#include "PivoxModels-Swift.h"
#define PIVOX_AI_CHAT_HAS_SWIFT_PROTOS 1
#else
#define PIVOX_AI_CHAT_HAS_SWIFT_PROTOS 0
#endif

namespace pivox::ai_chat {
class ChatClient;
}  // namespace pivox::ai_chat

// Retain/release declared in the global namespace so SWIFT_SHARED_REFERENCE
// can resolve them by unqualified name. Definitions at the bottom of this
// header (after ChatClient is complete).
void ChatClientRetain(pivox::ai_chat::ChatClient* c);
void ChatClientRelease(pivox::ai_chat::ChatClient* c);

namespace pivox::ai_chat {

// Internal reactor keeps std::function — not exposed to Swift.
using OnEvent = std::function<void(const uint8_t* bytes, size_t size)>;
using OnError = std::function<void(const std::string& msg)>;
using OnComplete = std::function<void()>;

// Server-stream reactor using bidi reactor with immediate half-close.
// Self-owning via shared_ptr released in OnDone.
class StreamReactor
    : public grpc::ClientBidiReactor<grpc::ByteBuffer, grpc::ByteBuffer> {
 public:
  static std::shared_ptr<StreamReactor> Create(
      std::unique_ptr<grpc::ClientContext> ctx,
      const grpc::ByteBuffer& request,
      OnEvent on_event, OnError on_error, OnComplete on_complete);

  void Start();
  void Detach();

  void OnWriteDone(bool ok) override;
  void OnReadDone(bool ok) override;
  void OnDone(const grpc::Status& status) override;

 private:
  StreamReactor(std::unique_ptr<grpc::ClientContext> ctx,
                const grpc::ByteBuffer& request,
                OnEvent on_event, OnError on_error, OnComplete on_complete);

  std::mutex cb_mu_;
  OnEvent on_event_;
  OnError on_error_;
  OnComplete on_complete_;

  std::unique_ptr<grpc::ClientContext> ctx_;
  std::shared_ptr<StreamReactor> self_;

  grpc::ByteBuffer request_;
  grpc::ByteBuffer read_buf_;
};

#if PIVOX_AI_CHAT_HAS_SWIFT_PROTOS
// Return value for all generated unary bridge methods. Plain C++ types
// only — generated methods can't return Swift-origin types by value
// (Swift 6.3 interop marks such methods "unavailable" on member funcs).
// Swift facade reads `code`/`message`, throws GRPCError if code != 0.
struct UnaryStatus {
  int32_t code;          // grpc::StatusCode raw; 0 == OK
  std::string message;   // populated on failure
};
#endif

class SWIFT_SHARED_REFERENCE(ChatClientRetain, ChatClientRelease) ChatClient {
 public:
  static SWIFT_RETURNS_RETAINED ChatClient* Create(
      const char* endpoint, const char* auth_token);

  ChatClient(const ChatClient&) = delete;
  ChatClient& operator=(const ChatClient&) = delete;

  void SetAuthToken(const char* token);
  void Cancel();

#if PIVOX_AI_CHAT_HAS_SWIFT_PROTOS
  // --- Apple typed entry points ---
  // Per-RPC method declarations generated by protoc-gen-pivox-cpp-bridge.
  // Each unary RPC: returns PivoxModels::Pivox_Google_Rpc_Status,
  // takes (const Request*, Response*). Server-stream: takes request +
  // callback triple (on_event with typed Swift proto pointer).
  //
  // TODO(swift-stdfunction): when Swift 6.4 lands closure↔std::function,
  // switch callbacks to std::function for cleaner call sites.
#include "ai_chat_bridge.h.inc"

  // Compat: bytes-based unary for not-yet-migrated call sites. Goes
  // away when ChatClient+Resources.swift migrates to typed generated
  // methods above.
  void UnaryCallBytes(
      const char* method,
      const uint8_t* request_bytes, size_t request_size,
      void* ctx,
      void (*on_response)(void* ctx, const uint8_t* bytes, size_t size),
      void (*on_error)(void* ctx, int32_t code, const char* message));
#endif

 private:
  ChatClient(const std::string& endpoint, const std::string& auth_token);
  ~ChatClient();

  // Internal bytes-based transport. Used by both typed wrappers above
  // and (in future) the WinRT port once typed C++ entry points land.
  void StartStreamBytes(const uint8_t* request_bytes, size_t request_size,
                        OnEvent on_event, OnError on_error,
                        OnComplete on_complete);
  grpc::Status DoUnaryCall(const char* method,
                           const uint8_t* request_bytes,
                           size_t request_size,
                           std::vector<uint8_t>* response_out);

  void OpenStream();
  void HandleStreamError(const std::string& msg);
  void Shutdown();

  friend void ::ChatClientRetain(ChatClient* c);
  friend void ::ChatClientRelease(ChatClient* c);

  std::atomic<int> ref_count_{1};

  std::shared_ptr<grpc::Channel> channel_;

  std::mutex mu_;
  std::condition_variable cv_;
  std::string auth_token_;
  std::shared_ptr<StreamReactor> reactor_;

  // Stream callback triple — lambdas bound in StartStream, kept as
  // std::function so the reactor thread can invoke them.
  OnEvent stream_on_event_;
  OnError stream_on_error_;
  OnComplete stream_on_complete_;
  std::vector<uint8_t> stream_request_;

  std::thread retry_thread_;
  int retry_count_ = 0;
  uint64_t generation_ = 0;
  bool shutdown_ = false;

  static constexpr int kMaxRetries = 3;
};

}  // namespace pivox::ai_chat

inline void ChatClientRetain(pivox::ai_chat::ChatClient* c) {
  if (c) c->ref_count_.fetch_add(1, std::memory_order_relaxed);
}

inline void ChatClientRelease(pivox::ai_chat::ChatClient* c) {
  if (c && c->ref_count_.fetch_sub(1, std::memory_order_acq_rel) == 1) {
    delete c;
  }
}

#endif  // PIVOX_AI_CHAT_CLIENT_H
