// Code generated by cmd/gen-permissions. DO NOT EDIT.
// Source: internal/permission/permissions.yaml

package permission

// Typed permission constants. Source of truth: permissions.yaml.
const (
	OrganizationsRead              = "organizations.read"
	OrganizationsUpdate            = "organizations.update"
	OrganizationsDelete            = "organizations.delete"
	OrganizationsTransferOwnership = "organizations.transferOwnership"
	OrganizationsSsoConfigRead     = "organizations.ssoConfig.read"
	OrganizationsSsoConfigUpdate   = "organizations.ssoConfig.update"
	SpacesCreate                   = "spaces.create"
	SpacesRead                     = "spaces.read"
	SpacesUpdate                   = "spaces.update"
	SpacesDelete                   = "spaces.delete"
	TagsCreate                     = "tags.create"
	TagsRead                       = "tags.read"
	TagsUpdate                     = "tags.update"
	TagsDelete                     = "tags.delete"
	SecretsCreate                  = "secrets.create"
	SecretsRead                    = "secrets.read"
	SecretsUpdate                  = "secrets.update"
	SecretsDelete                  = "secrets.delete"
	UsersRead                      = "users.read"
	UsersDelete                    = "users.delete"
	GroupsCreate                   = "groups.create"
	GroupsRead                     = "groups.read"
	GroupsUpdate                   = "groups.update"
	GroupsDelete                   = "groups.delete"
	GroupsManageMembers            = "groups.manageMembers"
	RolesCreate                    = "roles.create"
	RolesRead                      = "roles.read"
	RolesUpdate                    = "roles.update"
	RolesDelete                    = "roles.delete"
	RolesManageMembers             = "roles.manageMembers"
	InvitationsCreate              = "invitations.create"
	InvitationsRead                = "invitations.read"
	InvitationsDelete              = "invitations.delete"
	InvitationsUpdatePolicy        = "invitations.updatePolicy"
	ApiKeysCreate                  = "apiKeys.create"
	ApiKeysRead                    = "apiKeys.read"
	ApiKeysUpdate                  = "apiKeys.update"
	ApiKeysDelete                  = "apiKeys.delete"
	DashboardsRead                 = "dashboards.read"
	DashboardsCreate               = "dashboards.create"
	DashboardsUpdate               = "dashboards.update"
	DashboardsDelete               = "dashboards.delete"
	DomainsCreate                  = "domains.create"
	DomainsRead                    = "domains.read"
	DomainsDelete                  = "domains.delete"
	MembersCreate                  = "members.create"
	MembersRead                    = "members.read"
	MembersUpdate                  = "members.update"
	MembersDelete                  = "members.delete"
	StorageGatewaysCreate          = "storage.gateways.create"
	StorageGatewaysRead            = "storage.gateways.read"
	StorageGatewaysUpdate          = "storage.gateways.update"
	StorageGatewaysDelete          = "storage.gateways.delete"
	StorageGatewaysUpgrade         = "storage.gateways.upgrade"
	StorageEndpointsCreate         = "storage.endpoints.create"
	StorageEndpointsRead           = "storage.endpoints.read"
	StorageEndpointsUpdate         = "storage.endpoints.update"
	StorageEndpointsDelete         = "storage.endpoints.delete"
	StorageAgentsRead              = "storage.agents.read"
	StorageAgentsDrain             = "storage.agents.drain"
	StorageAgentsRemove            = "storage.agents.remove"
	AssetsAssetsRead               = "assets.assets.read"
	AssetsAssetsCreate             = "assets.assets.create"
	AssetsAssetsUpdate             = "assets.assets.update"
	AssetsAssetsDelete             = "assets.assets.delete"
	AssetsAssetsUndelete           = "assets.assets.undelete"
	AssetsAssetsImport             = "assets.assets.import"
	AssetsRequestsRead             = "assets.requests.read"
	AssetsRequestsCreate           = "assets.requests.create"
	AssetsRequestsUpdate           = "assets.requests.update"
	AssetsRequestsDelete           = "assets.requests.delete"
	AssetsRequestsAssign           = "assets.requests.assign"
	AssetsRequestsClaim            = "assets.requests.claim"
	AssetsRequestsSubmit           = "assets.requests.submit"
	AssetsRequestsDeliver          = "assets.requests.deliver"
	AssetsRequestsApprove          = "assets.requests.approve"
	AssetsRequestsReject           = "assets.requests.reject"
	AssetsRequestsCancel           = "assets.requests.cancel"
	AssetsLineItemsRead            = "assets.lineItems.read"
	AssetsLineItemsCreate          = "assets.lineItems.create"
	AssetsLineItemsUpdate          = "assets.lineItems.update"
	AssetsLineItemsDelete          = "assets.lineItems.delete"
	AssetsLineItemsFulfill         = "assets.lineItems.fulfill"
	AiConversationsRead            = "ai.conversations.read"
	AiConversationsCreate          = "ai.conversations.create"
	AiConversationsUpdate          = "ai.conversations.update"
	AiConversationsDelete          = "ai.conversations.delete"
	AiConversationsReadAll         = "ai.conversations.readAll"
	AiConversationsDeleteAll       = "ai.conversations.deleteAll"
	AiChatStream                   = "ai.chat.stream"
)

// All is the canonical, ordered list of every permission_id known
// to the v1 system. Order matches the YAML for stable downstream
// output.
var All = []string{
	OrganizationsRead,
	OrganizationsUpdate,
	OrganizationsDelete,
	OrganizationsTransferOwnership,
	OrganizationsSsoConfigRead,
	OrganizationsSsoConfigUpdate,
	SpacesCreate,
	SpacesRead,
	SpacesUpdate,
	SpacesDelete,
	TagsCreate,
	TagsRead,
	TagsUpdate,
	TagsDelete,
	SecretsCreate,
	SecretsRead,
	SecretsUpdate,
	SecretsDelete,
	UsersRead,
	UsersDelete,
	GroupsCreate,
	GroupsRead,
	GroupsUpdate,
	GroupsDelete,
	GroupsManageMembers,
	RolesCreate,
	RolesRead,
	RolesUpdate,
	RolesDelete,
	RolesManageMembers,
	InvitationsCreate,
	InvitationsRead,
	InvitationsDelete,
	InvitationsUpdatePolicy,
	ApiKeysCreate,
	ApiKeysRead,
	ApiKeysUpdate,
	ApiKeysDelete,
	DashboardsRead,
	DashboardsCreate,
	DashboardsUpdate,
	DashboardsDelete,
	DomainsCreate,
	DomainsRead,
	DomainsDelete,
	MembersCreate,
	MembersRead,
	MembersUpdate,
	MembersDelete,
	StorageGatewaysCreate,
	StorageGatewaysRead,
	StorageGatewaysUpdate,
	StorageGatewaysDelete,
	StorageGatewaysUpgrade,
	StorageEndpointsCreate,
	StorageEndpointsRead,
	StorageEndpointsUpdate,
	StorageEndpointsDelete,
	StorageAgentsRead,
	StorageAgentsDrain,
	StorageAgentsRemove,
	AssetsAssetsRead,
	AssetsAssetsCreate,
	AssetsAssetsUpdate,
	AssetsAssetsDelete,
	AssetsAssetsUndelete,
	AssetsAssetsImport,
	AssetsRequestsRead,
	AssetsRequestsCreate,
	AssetsRequestsUpdate,
	AssetsRequestsDelete,
	AssetsRequestsAssign,
	AssetsRequestsClaim,
	AssetsRequestsSubmit,
	AssetsRequestsDeliver,
	AssetsRequestsApprove,
	AssetsRequestsReject,
	AssetsRequestsCancel,
	AssetsLineItemsRead,
	AssetsLineItemsCreate,
	AssetsLineItemsUpdate,
	AssetsLineItemsDelete,
	AssetsLineItemsFulfill,
	AiConversationsRead,
	AiConversationsCreate,
	AiConversationsUpdate,
	AiConversationsDelete,
	AiConversationsReadAll,
	AiConversationsDeleteAll,
	AiChatStream,
}

// RoleGrants is the role-to-permission grant data, in ordered-slice
// form keyed by role name. Each role's set is the union of every
// permission whose `roles:` list mentions that role name in
// permissions.yaml. It seeds the role_permissions table (per-org
// system-role grants) at org bootstrap and in the dev seed, so
// permission checks resolve in SQL — the DB-side source of truth
// for authorization.
var RoleGrants = map[string][]string{
	RoleOwner: {
		AiChatStream,
		AiConversationsCreate,
		AiConversationsDelete,
		AiConversationsDeleteAll,
		AiConversationsRead,
		AiConversationsReadAll,
		AiConversationsUpdate,
		ApiKeysCreate,
		ApiKeysDelete,
		ApiKeysRead,
		ApiKeysUpdate,
		AssetsAssetsCreate,
		AssetsAssetsDelete,
		AssetsAssetsImport,
		AssetsAssetsRead,
		AssetsAssetsUndelete,
		AssetsAssetsUpdate,
		AssetsLineItemsCreate,
		AssetsLineItemsDelete,
		AssetsLineItemsFulfill,
		AssetsLineItemsRead,
		AssetsLineItemsUpdate,
		AssetsRequestsApprove,
		AssetsRequestsAssign,
		AssetsRequestsCancel,
		AssetsRequestsClaim,
		AssetsRequestsCreate,
		AssetsRequestsDelete,
		AssetsRequestsDeliver,
		AssetsRequestsRead,
		AssetsRequestsReject,
		AssetsRequestsSubmit,
		AssetsRequestsUpdate,
		DashboardsCreate,
		DashboardsDelete,
		DashboardsRead,
		DashboardsUpdate,
		DomainsCreate,
		DomainsDelete,
		DomainsRead,
		GroupsCreate,
		GroupsDelete,
		GroupsManageMembers,
		GroupsRead,
		GroupsUpdate,
		InvitationsCreate,
		InvitationsDelete,
		InvitationsRead,
		InvitationsUpdatePolicy,
		MembersCreate,
		MembersDelete,
		MembersRead,
		MembersUpdate,
		OrganizationsDelete,
		OrganizationsRead,
		OrganizationsSsoConfigRead,
		OrganizationsSsoConfigUpdate,
		OrganizationsTransferOwnership,
		OrganizationsUpdate,
		RolesCreate,
		RolesDelete,
		RolesManageMembers,
		RolesRead,
		RolesUpdate,
		SecretsCreate,
		SecretsDelete,
		SecretsRead,
		SecretsUpdate,
		SpacesCreate,
		SpacesDelete,
		SpacesRead,
		SpacesUpdate,
		StorageAgentsDrain,
		StorageAgentsRead,
		StorageAgentsRemove,
		StorageEndpointsCreate,
		StorageEndpointsDelete,
		StorageEndpointsRead,
		StorageEndpointsUpdate,
		StorageGatewaysCreate,
		StorageGatewaysDelete,
		StorageGatewaysRead,
		StorageGatewaysUpdate,
		StorageGatewaysUpgrade,
		TagsCreate,
		TagsDelete,
		TagsRead,
		TagsUpdate,
		UsersDelete,
		UsersRead,
	},
	RoleAdmin: {
		AiChatStream,
		AiConversationsCreate,
		AiConversationsDelete,
		AiConversationsRead,
		AiConversationsReadAll,
		AiConversationsUpdate,
		ApiKeysCreate,
		ApiKeysDelete,
		ApiKeysRead,
		ApiKeysUpdate,
		AssetsAssetsCreate,
		AssetsAssetsDelete,
		AssetsAssetsImport,
		AssetsAssetsRead,
		AssetsAssetsUndelete,
		AssetsAssetsUpdate,
		AssetsLineItemsCreate,
		AssetsLineItemsDelete,
		AssetsLineItemsFulfill,
		AssetsLineItemsRead,
		AssetsLineItemsUpdate,
		AssetsRequestsApprove,
		AssetsRequestsAssign,
		AssetsRequestsCancel,
		AssetsRequestsClaim,
		AssetsRequestsCreate,
		AssetsRequestsDelete,
		AssetsRequestsDeliver,
		AssetsRequestsRead,
		AssetsRequestsReject,
		AssetsRequestsSubmit,
		AssetsRequestsUpdate,
		DashboardsCreate,
		DashboardsDelete,
		DashboardsRead,
		DashboardsUpdate,
		DomainsCreate,
		DomainsDelete,
		DomainsRead,
		GroupsCreate,
		GroupsDelete,
		GroupsManageMembers,
		GroupsRead,
		GroupsUpdate,
		InvitationsCreate,
		InvitationsDelete,
		InvitationsRead,
		InvitationsUpdatePolicy,
		MembersCreate,
		MembersDelete,
		MembersRead,
		MembersUpdate,
		OrganizationsRead,
		OrganizationsSsoConfigRead,
		OrganizationsUpdate,
		RolesCreate,
		RolesDelete,
		RolesManageMembers,
		RolesRead,
		RolesUpdate,
		SecretsCreate,
		SecretsDelete,
		SecretsRead,
		SecretsUpdate,
		SpacesCreate,
		SpacesDelete,
		SpacesRead,
		SpacesUpdate,
		StorageAgentsDrain,
		StorageAgentsRead,
		StorageAgentsRemove,
		StorageEndpointsCreate,
		StorageEndpointsDelete,
		StorageEndpointsRead,
		StorageEndpointsUpdate,
		StorageGatewaysCreate,
		StorageGatewaysDelete,
		StorageGatewaysRead,
		StorageGatewaysUpdate,
		StorageGatewaysUpgrade,
		TagsCreate,
		TagsDelete,
		TagsRead,
		TagsUpdate,
		UsersRead,
	},
	RoleEditor: {
		AiChatStream,
		AiConversationsCreate,
		AiConversationsDelete,
		AiConversationsRead,
		AiConversationsUpdate,
		AssetsAssetsCreate,
		AssetsAssetsDelete,
		AssetsAssetsImport,
		AssetsAssetsRead,
		AssetsAssetsUndelete,
		AssetsAssetsUpdate,
		AssetsLineItemsCreate,
		AssetsLineItemsDelete,
		AssetsLineItemsFulfill,
		AssetsLineItemsRead,
		AssetsLineItemsUpdate,
		AssetsRequestsClaim,
		AssetsRequestsCreate,
		AssetsRequestsDelete,
		AssetsRequestsDeliver,
		AssetsRequestsRead,
		AssetsRequestsSubmit,
		AssetsRequestsUpdate,
		DashboardsRead,
		GroupsRead,
		OrganizationsRead,
		RolesRead,
		SecretsRead,
		SpacesRead,
		StorageAgentsRead,
		StorageEndpointsRead,
		StorageGatewaysRead,
		TagsRead,
		UsersRead,
	},
	RoleViewer: {
		AiChatStream,
		AiConversationsCreate,
		AiConversationsDelete,
		AiConversationsRead,
		AiConversationsUpdate,
		AssetsAssetsRead,
		AssetsLineItemsRead,
		AssetsRequestsRead,
		DashboardsRead,
		GroupsRead,
		OrganizationsRead,
		RolesRead,
		SpacesRead,
		StorageAgentsRead,
		StorageEndpointsRead,
		TagsRead,
		UsersRead,
	},
}
