// Code generated by cmd/gen-permissions. DO NOT EDIT.
// Source: internal/permission/permissions.yaml

package permission

// Typed permission constants. Source of truth: permissions.yaml.
const (
	OrganizationsRead              = "organizations.read"
	OrganizationsUpdate            = "organizations.update"
	OrganizationsDelete            = "organizations.delete"
	OrganizationsTransferOwnership = "organizations.transferOwnership"
	OrganizationsSsoConfigRead     = "organizations.ssoConfig.read"
	OrganizationsSsoConfigUpdate   = "organizations.ssoConfig.update"
	SpacesCreate                   = "spaces.create"
	SpacesRead                     = "spaces.read"
	SpacesUpdate                   = "spaces.update"
	SpacesDelete                   = "spaces.delete"
	TagsCreate                     = "tags.create"
	TagsRead                       = "tags.read"
	TagsUpdate                     = "tags.update"
	TagsDelete                     = "tags.delete"
	UsersRead                      = "users.read"
	UsersDelete                    = "users.delete"
	GroupsCreate                   = "groups.create"
	GroupsRead                     = "groups.read"
	GroupsUpdate                   = "groups.update"
	GroupsDelete                   = "groups.delete"
	GroupsManageMembers            = "groups.manageMembers"
	RolesCreate                    = "roles.create"
	RolesRead                      = "roles.read"
	RolesUpdate                    = "roles.update"
	RolesDelete                    = "roles.delete"
	RolesManageMembers             = "roles.manageMembers"
	InvitationsCreate              = "invitations.create"
	InvitationsRead                = "invitations.read"
	InvitationsDelete              = "invitations.delete"
	InvitationsUpdatePolicy        = "invitations.updatePolicy"
	ApiKeysCreate                  = "apiKeys.create"
	ApiKeysRead                    = "apiKeys.read"
	ApiKeysUpdate                  = "apiKeys.update"
	ApiKeysDelete                  = "apiKeys.delete"
	DomainsCreate                  = "domains.create"
	DomainsRead                    = "domains.read"
	DomainsDelete                  = "domains.delete"
	MembersCreate                  = "members.create"
	MembersRead                    = "members.read"
	MembersUpdate                  = "members.update"
	MembersDelete                  = "members.delete"
	StorageGatewaysCreate          = "storage.gateways.create"
	StorageGatewaysRead            = "storage.gateways.read"
	StorageGatewaysUpdate          = "storage.gateways.update"
	StorageGatewaysDelete          = "storage.gateways.delete"
	StorageGatewaysUpgrade         = "storage.gateways.upgrade"
	StorageEndpointsCreate         = "storage.endpoints.create"
	StorageEndpointsRead           = "storage.endpoints.read"
	StorageEndpointsUpdate         = "storage.endpoints.update"
	StorageEndpointsDelete         = "storage.endpoints.delete"
	StorageAgentsRead              = "storage.agents.read"
	StorageAgentsDrain             = "storage.agents.drain"
	StorageAgentsRemove            = "storage.agents.remove"
	AssetsAssetsRead               = "assets.assets.read"
	AssetsAssetsCreate             = "assets.assets.create"
	AssetsAssetsUpdate             = "assets.assets.update"
	AssetsAssetsDelete             = "assets.assets.delete"
	AssetsAssetsUndelete           = "assets.assets.undelete"
	AssetsAssetsImport             = "assets.assets.import"
	AssetsRequestsRead             = "assets.requests.read"
	AssetsRequestsCreate           = "assets.requests.create"
	AssetsRequestsUpdate           = "assets.requests.update"
	AssetsRequestsDelete           = "assets.requests.delete"
	AssetsRequestsAssign           = "assets.requests.assign"
	AssetsRequestsClaim            = "assets.requests.claim"
	AssetsRequestsSubmit           = "assets.requests.submit"
	AssetsRequestsDeliver          = "assets.requests.deliver"
	AssetsRequestsApprove          = "assets.requests.approve"
	AssetsRequestsReject           = "assets.requests.reject"
	AssetsRequestsCancel           = "assets.requests.cancel"
	AssetsLineItemsRead            = "assets.lineItems.read"
	AssetsLineItemsCreate          = "assets.lineItems.create"
	AssetsLineItemsUpdate          = "assets.lineItems.update"
	AssetsLineItemsDelete          = "assets.lineItems.delete"
	AssetsLineItemsFulfill         = "assets.lineItems.fulfill"
	AiConversationsRead            = "ai.conversations.read"
	AiConversationsCreate          = "ai.conversations.create"
	AiConversationsUpdate          = "ai.conversations.update"
	AiConversationsDelete          = "ai.conversations.delete"
	AiChatStream                   = "ai.chat.stream"
)

// All is the canonical, ordered list of every permission_id known
// to the v1 system. Order matches the YAML for stable downstream
// output.
var All = []string{
	OrganizationsRead,
	OrganizationsUpdate,
	OrganizationsDelete,
	OrganizationsTransferOwnership,
	OrganizationsSsoConfigRead,
	OrganizationsSsoConfigUpdate,
	SpacesCreate,
	SpacesRead,
	SpacesUpdate,
	SpacesDelete,
	TagsCreate,
	TagsRead,
	TagsUpdate,
	TagsDelete,
	UsersRead,
	UsersDelete,
	GroupsCreate,
	GroupsRead,
	GroupsUpdate,
	GroupsDelete,
	GroupsManageMembers,
	RolesCreate,
	RolesRead,
	RolesUpdate,
	RolesDelete,
	RolesManageMembers,
	InvitationsCreate,
	InvitationsRead,
	InvitationsDelete,
	InvitationsUpdatePolicy,
	ApiKeysCreate,
	ApiKeysRead,
	ApiKeysUpdate,
	ApiKeysDelete,
	DomainsCreate,
	DomainsRead,
	DomainsDelete,
	MembersCreate,
	MembersRead,
	MembersUpdate,
	MembersDelete,
	StorageGatewaysCreate,
	StorageGatewaysRead,
	StorageGatewaysUpdate,
	StorageGatewaysDelete,
	StorageGatewaysUpgrade,
	StorageEndpointsCreate,
	StorageEndpointsRead,
	StorageEndpointsUpdate,
	StorageEndpointsDelete,
	StorageAgentsRead,
	StorageAgentsDrain,
	StorageAgentsRemove,
	AssetsAssetsRead,
	AssetsAssetsCreate,
	AssetsAssetsUpdate,
	AssetsAssetsDelete,
	AssetsAssetsUndelete,
	AssetsAssetsImport,
	AssetsRequestsRead,
	AssetsRequestsCreate,
	AssetsRequestsUpdate,
	AssetsRequestsDelete,
	AssetsRequestsAssign,
	AssetsRequestsClaim,
	AssetsRequestsSubmit,
	AssetsRequestsDeliver,
	AssetsRequestsApprove,
	AssetsRequestsReject,
	AssetsRequestsCancel,
	AssetsLineItemsRead,
	AssetsLineItemsCreate,
	AssetsLineItemsUpdate,
	AssetsLineItemsDelete,
	AssetsLineItemsFulfill,
	AiConversationsRead,
	AiConversationsCreate,
	AiConversationsUpdate,
	AiConversationsDelete,
	AiChatStream,
}

// matrix is the role-to-permission grant map. Each role's set is
// the union of every permission whose `roles:` list mentions that
// role name in permissions.yaml.
var matrix = map[string]map[string]bool{
	RoleOwner: {
		AiChatStream:                   true,
		AiConversationsCreate:          true,
		AiConversationsDelete:          true,
		AiConversationsRead:            true,
		AiConversationsUpdate:          true,
		ApiKeysCreate:                  true,
		ApiKeysDelete:                  true,
		ApiKeysRead:                    true,
		ApiKeysUpdate:                  true,
		AssetsAssetsCreate:             true,
		AssetsAssetsDelete:             true,
		AssetsAssetsImport:             true,
		AssetsAssetsRead:               true,
		AssetsAssetsUndelete:           true,
		AssetsAssetsUpdate:             true,
		AssetsLineItemsCreate:          true,
		AssetsLineItemsDelete:          true,
		AssetsLineItemsFulfill:         true,
		AssetsLineItemsRead:            true,
		AssetsLineItemsUpdate:          true,
		AssetsRequestsApprove:          true,
		AssetsRequestsAssign:           true,
		AssetsRequestsCancel:           true,
		AssetsRequestsClaim:            true,
		AssetsRequestsCreate:           true,
		AssetsRequestsDelete:           true,
		AssetsRequestsDeliver:          true,
		AssetsRequestsRead:             true,
		AssetsRequestsReject:           true,
		AssetsRequestsSubmit:           true,
		AssetsRequestsUpdate:           true,
		DomainsCreate:                  true,
		DomainsDelete:                  true,
		DomainsRead:                    true,
		GroupsCreate:                   true,
		GroupsDelete:                   true,
		GroupsManageMembers:            true,
		GroupsRead:                     true,
		GroupsUpdate:                   true,
		InvitationsCreate:              true,
		InvitationsDelete:              true,
		InvitationsRead:                true,
		InvitationsUpdatePolicy:        true,
		MembersCreate:                  true,
		MembersDelete:                  true,
		MembersRead:                    true,
		MembersUpdate:                  true,
		OrganizationsDelete:            true,
		OrganizationsRead:              true,
		OrganizationsSsoConfigRead:     true,
		OrganizationsSsoConfigUpdate:   true,
		OrganizationsTransferOwnership: true,
		OrganizationsUpdate:            true,
		RolesCreate:                    true,
		RolesDelete:                    true,
		RolesManageMembers:             true,
		RolesRead:                      true,
		RolesUpdate:                    true,
		SpacesCreate:                   true,
		SpacesDelete:                   true,
		SpacesRead:                     true,
		SpacesUpdate:                   true,
		StorageAgentsDrain:             true,
		StorageAgentsRead:              true,
		StorageAgentsRemove:            true,
		StorageEndpointsCreate:         true,
		StorageEndpointsDelete:         true,
		StorageEndpointsRead:           true,
		StorageEndpointsUpdate:         true,
		StorageGatewaysCreate:          true,
		StorageGatewaysDelete:          true,
		StorageGatewaysRead:            true,
		StorageGatewaysUpdate:          true,
		StorageGatewaysUpgrade:         true,
		TagsCreate:                     true,
		TagsDelete:                     true,
		TagsRead:                       true,
		TagsUpdate:                     true,
		UsersDelete:                    true,
		UsersRead:                      true,
	},
	RoleAdmin: {
		AiChatStream:               true,
		AiConversationsCreate:      true,
		AiConversationsDelete:      true,
		AiConversationsRead:        true,
		AiConversationsUpdate:      true,
		ApiKeysCreate:              true,
		ApiKeysDelete:              true,
		ApiKeysRead:                true,
		ApiKeysUpdate:              true,
		AssetsAssetsCreate:         true,
		AssetsAssetsDelete:         true,
		AssetsAssetsImport:         true,
		AssetsAssetsRead:           true,
		AssetsAssetsUndelete:       true,
		AssetsAssetsUpdate:         true,
		AssetsLineItemsCreate:      true,
		AssetsLineItemsDelete:      true,
		AssetsLineItemsFulfill:     true,
		AssetsLineItemsRead:        true,
		AssetsLineItemsUpdate:      true,
		AssetsRequestsApprove:      true,
		AssetsRequestsAssign:       true,
		AssetsRequestsCancel:       true,
		AssetsRequestsClaim:        true,
		AssetsRequestsCreate:       true,
		AssetsRequestsDelete:       true,
		AssetsRequestsDeliver:      true,
		AssetsRequestsRead:         true,
		AssetsRequestsReject:       true,
		AssetsRequestsSubmit:       true,
		AssetsRequestsUpdate:       true,
		DomainsCreate:              true,
		DomainsDelete:              true,
		DomainsRead:                true,
		GroupsCreate:               true,
		GroupsDelete:               true,
		GroupsManageMembers:        true,
		GroupsRead:                 true,
		GroupsUpdate:               true,
		InvitationsCreate:          true,
		InvitationsDelete:          true,
		InvitationsRead:            true,
		InvitationsUpdatePolicy:    true,
		MembersCreate:              true,
		MembersDelete:              true,
		MembersRead:                true,
		MembersUpdate:              true,
		OrganizationsRead:          true,
		OrganizationsSsoConfigRead: true,
		OrganizationsUpdate:        true,
		RolesCreate:                true,
		RolesDelete:                true,
		RolesManageMembers:         true,
		RolesRead:                  true,
		RolesUpdate:                true,
		SpacesCreate:               true,
		SpacesDelete:               true,
		SpacesRead:                 true,
		SpacesUpdate:               true,
		StorageAgentsDrain:         true,
		StorageAgentsRead:          true,
		StorageAgentsRemove:        true,
		StorageEndpointsCreate:     true,
		StorageEndpointsDelete:     true,
		StorageEndpointsRead:       true,
		StorageEndpointsUpdate:     true,
		StorageGatewaysCreate:      true,
		StorageGatewaysDelete:      true,
		StorageGatewaysRead:        true,
		StorageGatewaysUpdate:      true,
		StorageGatewaysUpgrade:     true,
		TagsCreate:                 true,
		TagsDelete:                 true,
		TagsRead:                   true,
		TagsUpdate:                 true,
		UsersRead:                  true,
	},
	RoleEditor: {
		AiChatStream:           true,
		AiConversationsCreate:  true,
		AiConversationsDelete:  true,
		AiConversationsRead:    true,
		AiConversationsUpdate:  true,
		AssetsAssetsCreate:     true,
		AssetsAssetsDelete:     true,
		AssetsAssetsImport:     true,
		AssetsAssetsRead:       true,
		AssetsAssetsUndelete:   true,
		AssetsAssetsUpdate:     true,
		AssetsLineItemsCreate:  true,
		AssetsLineItemsDelete:  true,
		AssetsLineItemsFulfill: true,
		AssetsLineItemsRead:    true,
		AssetsLineItemsUpdate:  true,
		AssetsRequestsClaim:    true,
		AssetsRequestsCreate:   true,
		AssetsRequestsDelete:   true,
		AssetsRequestsDeliver:  true,
		AssetsRequestsRead:     true,
		AssetsRequestsSubmit:   true,
		AssetsRequestsUpdate:   true,
		GroupsRead:             true,
		OrganizationsRead:      true,
		RolesRead:              true,
		SpacesRead:             true,
		StorageAgentsRead:      true,
		StorageEndpointsRead:   true,
		StorageGatewaysRead:    true,
		TagsRead:               true,
		UsersRead:              true,
	},
	RoleViewer: {
		AiConversationsRead:  true,
		AssetsAssetsRead:     true,
		AssetsLineItemsRead:  true,
		AssetsRequestsRead:   true,
		GroupsRead:           true,
		OrganizationsRead:    true,
		RolesRead:            true,
		SpacesRead:           true,
		StorageAgentsRead:    true,
		StorageEndpointsRead: true,
		TagsRead:             true,
		UsersRead:            true,
	},
}
