// protoc-gen-pivox-swift-facade
//
// Emits Swift `async throws` app-facing wrappers on top of the generated
// Apple C++ bridge methods (from protoc-gen-pivox-cpp-bridge). Hides the
// withUnsafePointer / OpaquePointer dance required by Swift 6.3 interop
// constraints (Swift-origin types cross only as pointer, imported as
// OpaquePointer).
//
// App code calls these:
//
//	let resp = try await client.listMessages(req)
//	for try await event in client.stream(clientEvent) { ... }
//
// Output: one `<Service>+Facade.swift` per service. Methods are added to
// `ChatClient` via a `public extension`. Requires the hand-written
// `ChatClient` class to expose its underlying C++ instance via the
// `cpp` property at internal visibility (not private) so extension
// methods in the same module can reach it.
//
// Retirement trigger: Swift 6.4+ binds Swift closures to std::function
// AND preserves Swift-origin types as typed params / return values (no
// OpaquePointer erasure). At that point the facade layer offers no
// meaningful ergonomic value and the cpp-bridge can be called directly.
package main

import (
	"flag"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/dashkan/pivox/tools/internal/pivoxgen"
)

func main() {
	var flags flag.FlagSet
	var opts pivoxgen.CommonOptions
	pivoxgen.RegisterCommonFlags(&flags, &opts)

	protogen.Options{ParamFunc: flags.Set}.Run(func(p *protogen.Plugin) error {
		pivoxgen.SetSupportedFeatures(p)

		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			if len(f.Services) == 0 {
				continue
			}
			for _, svc := range f.Services {
				if !pivoxgen.ShouldGenerateService(&opts, string(svc.Desc.FullName())) {
					continue
				}
				if err := emitService(p, svc); err != nil {
					return fmt.Errorf("%s: %w", svc.Desc.FullName(), err)
				}
			}
		}
		return nil
	})
}

func emitService(p *protogen.Plugin, svc *protogen.Service) error {
	name := fmt.Sprintf("%s+Facade.swift", svc.GoName)
	g := p.NewGeneratedFile(name, "")

	g.P("// Generated by protoc-gen-pivox-swift-facade. DO NOT EDIT.")
	g.P("// source: ", svc.Desc.ParentFile().Path())
	g.P("// service: ", svc.Desc.FullName())
	g.P()
	g.P("import Foundation")
	g.P("import PivoxModels")
	g.P()

	// Stream context classes first, one per server-streaming RPC (each
	// carries a differently-typed AsyncThrowingStream continuation).
	// Client-stream + bidi skipped — see TODO below.
	for _, m := range svc.Methods {
		if !shouldEmit(m) {
			continue
		}
		if rpcKindOf(m) == rpcServerStream {
			emitStreamContext(g, m)
		}
	}

	g.P("public extension ChatClient {")
	for _, m := range svc.Methods {
		if !shouldEmit(m) {
			g.P("    // ", m.Desc.FullName(), " — skipped: input/output type lives outside PivoxModels")
			g.P()
			continue
		}
		g.P("    // ", m.Desc.FullName())
		switch rpcKindOf(m) {
		case rpcUnary:
			emitUnaryFacade(g, m)
		case rpcServerStream:
			emitStreamFacade(g, m)
		case rpcClientStream, rpcBidi:
			g.P("    // TODO(bidi-gen): ", rpcKindOf(m), " not yet supported by")
			g.P("    //   protoc-gen-pivox-swift-facade. Matching cpp-bridge stub;")
			g.P("    //   design the Swift API (likely an actor-like object exposing")
			g.P("    //   send(request) + AsyncThrowingStream<Response>) when a real")
			g.P("    //   bidi/client-stream RPC is added.")
		}
		g.P()
	}
	g.P("}")
	return nil
}

// rpcKind mirrors the cpp-bridge generator's classification so both
// sides branch identically on the same RPC.
type rpcKind int

const (
	rpcUnary rpcKind = iota
	rpcServerStream
	rpcClientStream
	rpcBidi
)

func (k rpcKind) String() string {
	switch k {
	case rpcUnary:
		return "unary"
	case rpcServerStream:
		return "server-stream"
	case rpcClientStream:
		return "client-stream"
	case rpcBidi:
		return "bidi"
	}
	return "unknown"
}

func rpcKindOf(m *protogen.Method) rpcKind {
	cs := m.Desc.IsStreamingClient()
	ss := m.Desc.IsStreamingServer()
	switch {
	case cs && ss:
		return rpcBidi
	case cs:
		return rpcClientStream
	case ss:
		return rpcServerStream
	default:
		return rpcUnary
	}
}

func emitUnaryFacade(g *protogen.GeneratedFile, m *protogen.Method) {
	swiftMethod := swiftLowerFirst(m.GoName)
	reqT := swiftTypeName(m.Input)
	respT := swiftTypeName(m.Output)

	g.P("    func ", swiftMethod, "(")
	g.P("        _ request: ", reqT)
	g.P("    ) async throws -> ", respT, " {")
	g.P("        var req = request")
	g.P("        var resp = ", respT, "()")
	g.P("        let status = withUnsafePointer(to: &req) { reqPtr in")
	g.P("            withUnsafeMutablePointer(to: &resp) { respPtr in")
	g.P("                cpp.", m.GoName, "(OpaquePointer(reqPtr), OpaquePointer(respPtr))")
	g.P("            }")
	g.P("        }")
	g.P("        if status.code != 0 {")
	g.P("            throw GRPCError(code: status.code, message: String(status.message))")
	g.P("        }")
	g.P("        return resp")
	g.P("    }")
}

func emitStreamFacade(g *protogen.GeneratedFile, m *protogen.Method) {
	swiftMethod := swiftLowerFirst(m.GoName)
	reqT := swiftTypeName(m.Input)
	respT := swiftTypeName(m.Output)
	ctxT := streamContextClassName(m)

	g.P("    func ", swiftMethod, "(")
	g.P("        _ request: ", reqT)
	g.P("    ) -> AsyncThrowingStream<", respT, ", Error> {")
	g.P("        return AsyncThrowingStream { continuation in")
	g.P("            let ctx = Unmanaged.passRetained(", ctxT, "(continuation: continuation))")
	g.P("            var requestCopy = request")
	g.P("            withUnsafePointer(to: &requestCopy) { reqPtr in")
	g.P("                cpp.", m.GoName, "(")
	g.P("                    OpaquePointer(reqPtr),")
	g.P("                    ctx.toOpaque(),")
	g.P("                    { rawCtx, eventOpaque in")
	g.P("                        guard let rawCtx else { return }")
	g.P("                        let c = Unmanaged<", ctxT, ">.fromOpaque(rawCtx).takeUnretainedValue()")
	g.P("                        if let op = eventOpaque {")
	g.P("                            let typedPtr = UnsafePointer<", respT, ">(op)")
	g.P("                            c.continuation.yield(typedPtr.pointee)")
	g.P("                        }")
	g.P("                    },")
	g.P("                    { rawCtx, code, msg in")
	g.P("                        guard let rawCtx else { return }")
	g.P("                        let c = Unmanaged<", ctxT, ">.fromOpaque(rawCtx).takeRetainedValue()")
	g.P("                        let text = msg.map { String(cString: $0) } ?? \"stream error\"")
	g.P("                        c.continuation.finish(throwing: GRPCError(code: code, message: text))")
	g.P("                    },")
	g.P("                    { rawCtx in")
	g.P("                        guard let rawCtx else { return }")
	g.P("                        let c = Unmanaged<", ctxT, ">.fromOpaque(rawCtx).takeRetainedValue()")
	g.P("                        c.continuation.finish()")
	g.P("                    }")
	g.P("                )")
	g.P("            }")
	g.P("            let client = cpp")
	g.P("            continuation.onTermination = { _ in client.Cancel() }")
	g.P("        }")
	g.P("    }")
}

func emitStreamContext(g *protogen.GeneratedFile, m *protogen.Method) {
	respT := swiftTypeName(m.Output)
	ctxT := streamContextClassName(m)
	g.P("private final class ", ctxT, " {")
	g.P("    let continuation: AsyncThrowingStream<", respT, ", Error>.Continuation")
	g.P("    init(continuation: AsyncThrowingStream<", respT, ", Error>.Continuation) {")
	g.P("        self.continuation = continuation")
	g.P("    }")
	g.P("}")
	g.P()
}

// --- Shared helpers ---

func shouldEmit(m *protogen.Method) bool {
	return pkgIsPivoxModels(m.Input) && pkgIsPivoxModels(m.Output)
}

func pkgIsPivoxModels(msg *protogen.Message) bool {
	pkg := string(msg.Desc.ParentFile().Package())
	return !strings.HasPrefix(pkg, "google.protobuf")
}

// swiftTypeName returns the unqualified Swift type name — e.g.
// `Pivox_Ai_V1_ListMessagesRequest`. Swift call sites don't write the
// `PivoxModels::` module prefix (that's only needed on the C++ side).
func swiftTypeName(m *protogen.Message) string {
	pkg := string(m.Desc.ParentFile().Package())
	parts := strings.Split(pkg, ".")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = upperFirst(p)
	}
	prefix := strings.Join(parts, "_")
	if prefix != "" {
		prefix += "_"
	}
	return prefix + string(m.Desc.Name())
}

func swiftLowerFirst(s string) string {
	if s == "" {
		return s
	}
	if s[0] >= 'A' && s[0] <= 'Z' {
		return string(s[0]-'A'+'a') + s[1:]
	}
	return s
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	if s[0] >= 'a' && s[0] <= 'z' {
		return string(s[0]-'a'+'A') + s[1:]
	}
	return s
}

func streamContextClassName(m *protogen.Method) string {
	return "_StreamCtx_" + m.GoName
}
